const en = {
  label: "Appointments",
  description: "Manage your bookings.",
  header_title: "Appointments",
  header_subtitle: "Manage your bookings",
  home_body: "Schedule and manage appointments.",
  details_title: "Appointment Details",
  details_body: "Appointment details and reminders.",
  details_meta_category: "Category",
  details_meta_distance: "Distance",
  details_meta_rating: "Rating",
  details_meta_offer: "Offer",
  details_meta_hours_fallback: "Closed today",
  details_closed_badge: "Closed",
  details_closed_notice:
    "This store is currently closed, so ordering is temporarily unavailable.",
  details_closed_overlay_title: "Store is closed",
  details_closed_overlay_body:
    "Ordering is disabled until this store becomes available again.",
  details_action_back: "Go back",
  details_action_info: "Store information",
  details_action_share: "Share store",
  details_about_title: "About",
  details_close: "Close",
  details_open_until: "Open until {{time}}",
  details_timing_closed: "Closed",
  details_team_role_fallback: "Staff",
  details_service_meta_fallback: "1 hr",
  details_search_placeholder: "Search services",
  details_services_title: "All Offered Services",
  details_services_empty: "No services matched this selection yet.",
  details_store_missing: "This appointment provider could not be opened.",
  details_load_error: "We could not load this appointment provider right now.",
  details_tab_all: "All",
  details_get_in_touch: "Get in touch",
  details_our_services: "Our services",
  details_team: "Team",
  details_reviews: "Reviews",
  details_opening_times: "Opening times",
  details_additional_info: "Additional info",
  details_book_now: "Book Now",
  details_book_now_short: "Book",
  details_services_available: "{{count}} services available",
  details_reviews_count: "{{count}} reviews",
  details_rating_with_count: "{{rating}} ({{count}} reviews)",
  details_get_directions: "Get directions",
  details_team_empty: "No team information available yet.",
  details_reviews_empty: "There are no reviews yet.",
  details_info_phone: "Phone support available",
  details_info_email: "Email contact available",
  details_info_online_booking: "Online booking available",
  details_info_available_today: "Appointments available today",
  team_screen_title: "Team",
  team_any_professional: "Any professional",
  team_any_professional_subtitle: "For maximum availability",
  team_select: "Select",
  team_select_info_title: "Team selection",
  team_select_info_body:
    "Worker selection will be connected in the booking flow next.",
  team_schedule_date_time_confirm: "Choose date and time",
  team_schedule_picker_confirm: "Confirm date & time",
  team_schedule_available_slots_title: "Choose an available time",
  team_schedule_available_times: "Available times",
  team_schedule_today: "Today",
  team_schedule_loading_slots: "Loading available times…",
  team_schedule_no_slots:
    "No times are available on this date. Please choose another date.",
  team_schedule_slot_taken_title: "Time no longer available",
  team_schedule_slot_taken_body:
    "Availability was refreshed. Please select another time.",
  team_schedule_unavailable_title: "Selected slot unavailable",
  team_schedule_unavailable_body:
    "Please choose another date or time for this appointment.",
  team_schedule_error_title: "Unable to continue booking",
  team_schedule_error_body: "We could not load booking availability right now.",
  services_screen_title: "Services",
  services_variants_label: "Available variants",
  services_select_info_body:
    "Service customization will be connected in the booking flow next.",
  services_selection_info_title: "Service selection",
  services_selection_info_body: "Select any service to proceed.",
  services_clear_selection: "Clear selected services",
  services_continue: "Continue",
  services_selected_count_one: "{{count}} service",
  services_selected_count_other: "{{count}} services",
  cart_store_conflict_title: "Replace your current cart?",
  cart_store_conflict_body:
    "Your cart contains services from another store. Remove them and add services from {{store}}?",
  cart_store_conflict_keep: "Keep current cart",
  cart_store_conflict_replace: "Replace cart",
  cart_save_error_title: "Cart could not be saved",
  cart_save_error_body: "Please try adding these services again.",
  review_confirm_title: "Review and confirm",
  review_confirm_professional_title: "Professional",
  review_confirm_payment_title: "Payment",
  review_confirm_payment_cash: "Pay after service",
  review_confirm_payment_stripe: "Card",
  review_confirm_payment_change_hint: "Tap here to change",
  review_confirm_discount_title: "Discount code",
  review_confirm_discount_hint: "Tap here to continue",
  review_confirm_payment_missing_title: "Payment unavailable",
  review_confirm_payment_missing_body:
    "No supported payment method is available for this booking yet.",
  review_confirm_notes_title: "Notes",
  review_confirm_notes_optional: "Optional",
  review_confirm_notes_placeholder: "Add any instructions for this appointment",
  review_confirm_cancellation_title: "Cancellation policy",
  review_confirm_total_title: "Total",
  review_confirm_total_subtitle: "incl. taxes (if applicable)",
  review_confirm_any_professional: "Any professional",
  review_confirm_footer_cta: "Confirm",
  review_confirm_popup_title: "Cancellation policy",
  review_confirm_popup_accept: "Accept and confirm",
  review_confirm_appointment_confirmed: "Appointment confirmed",
  review_confirm_success_body:
    "Your booking with {{storeName}} has been confirmed. Order ID: {{orderId}}.",
  review_confirm_success_bookings: "Go to bookings",
  review_confirm_success_home: "Back to home",
  review_confirm_place_order_error_title: "Unable to confirm booking",
  review_confirm_place_order_error_body: "Please try again in a moment.",
  review_confirm_discount_selected:
    "{{code}} selected. Eligibility will be checked when you confirm.",
  review_confirm_discount_refreshing: "Updating your appointment total…",
  review_confirm_discount_applied: "{{code}} applied · You save {{value}}",
  coupons_title: "Coupons",
  coupons_description:
    "Enter a coupon code or choose an available offer for your appointment.",
  coupons_placeholder: "Enter coupon code",
  coupons_apply: "Apply coupon",
  coupons_off: "OFF",
  coupons_minimum: "Minimum booking: ${{value}}",
  coupons_valid_until: "Valid until {{date}}",
  coupons_use: "Use coupon",
  coupons_deactivate: "Deactivate",
  coupons_applied_title: "Coupon applied",
  coupons_applied_body: "Your appointment total will be updated at checkout.",
  coupons_removed_title: "Coupon removed",
  coupons_removed_body: "The coupon is no longer applied.",
  coupons_error_title: "Coupon unavailable",
  coupons_error_body: "Please try again in a moment.",
  coupons_invalid_code: "Enter a valid active coupon code.",
  coupons_load_error: "Coupons could not be loaded. Pull to retry.",
  coupons_empty_title: "No coupons available",
  coupons_empty_body: "New appointment offers will appear here.",
  cart_title: "Cart",
  cart_clear_action: "Clear cart",
  cart_empty_title: "Nothing here yet",
  cart_empty_body:
    "Add services to your cart so you can come back and continue booking anytime.",
  cart_empty_action: "Select service",
  favourites_title: "Your Favourites",
  favourites_empty_title: "No favourites yet",
  favourites_empty_subtitle: "Stores you favourite will appear here.",
  favourites_error: "Failed to load favourites. Pull down to retry.",
  favourites_toggle_added: "Added to favourites",
  favourites_toggle_removed: "Removed from favourites",
  favourites_toggle_error: "Failed to update favourites",
  favourites_services_title: "Favourite Services",
  favourites_services_empty_title: "No favourite services yet",
  favourites_services_empty_message:
    "Services you favourite from this provider will appear here.",
  favourites_service_added: "Service added to favourites",
  favourites_service_removed: "Service removed from favourites",
  bookings_title: "Appointments",
  bookings_my_appointments_title: "My appointments",
  bookings_upcoming_title: "Upcoming",
  bookings_completed_title: "Completed",
  bookings_cancelled_title: "Cancelled",
  bookings_past_title: "Past",
  bookings_empty_title: "No appointments found",
  bookings_empty_subtitle:
    "Your upcoming and past appointments will appear when you book.",
  bookings_empty_action: "Search providers",
  bookings_upcoming_empty_title: "No upcoming appointments",
  bookings_upcoming_empty_subtitle:
    "Your next booking will appear here once it is confirmed.",
  bookings_completed_empty_title: "No completed appointments",
  bookings_completed_empty_subtitle:
    "Appointments you complete will appear here.",
  bookings_cancelled_empty_title: "No cancelled appointments",
  bookings_cancelled_empty_subtitle:
    "Appointments you cancel will appear here.",
  bookings_past_summary: "Appointment service",
  bookings_error_title: "Unable to load appointments",
  bookings_error_subtitle: "Pull to refresh or try again in a moment.",
  bookings_retry: "Retry",
  bookings_book_again: "Book again",
  bookings_scheduled_badge: "Scheduled",
  bookings_meta_items_one: "{{count}} item",
  bookings_meta_items_other: "{{count}} items",
  bookings_meta_time_pending: "Scheduled appointment",
  bookings_get_directions: "Get directions",
  bookings_date_title: "Appointment date",
  bookings_location_unavailable: "Store location is unavailable.",
  booking_detail_error_title: "Unable to load this appointment",
  booking_detail_duration: "{{duration}} duration",
  booking_detail_add_calendar: "Add to calendar",
  booking_detail_add_calendar_subtitle: "Set yourself a reminder",
  booking_detail_getting_there: "Getting there",
  booking_detail_manage: "Manage appointment",
  booking_detail_manage_subtitle: "Choose a new date and time",
  booking_detail_cancel: "Cancel booking",
  booking_detail_cancel_available:
    "Available until 2 hours before the appointment",
  booking_detail_cancel_unavailable:
    "Cancellation is unavailable within 2 hours of the appointment",
  booking_detail_cancel_confirm_title: "Cancel this booking?",
  booking_detail_cancel_confirm_body: "This action cannot be undone.",
  booking_detail_cancel_confirm_action: "Cancel booking",
  booking_detail_cancel_success_title: "Booking cancelled",
  booking_detail_cancel_success_body: "Your appointment has been cancelled.",
  booking_detail_cancel_error_title: "Unable to cancel booking",
  booking_detail_cancel_error_body:
    "This appointment may be inside the two-hour cancellation cutoff.",
  booking_detail_manage_unavailable:
    "Appointment changes are not available yet. Please contact the venue.",
  booking_detail_venue: "Venue details",
  booking_detail_overview: "Overview",
  booking_detail_total: "Total",
  booking_detail_service_fee: "Service fee",
  booking_detail_reschedule_now: "Reschedule now",
  booking_detail_reschedule_success_title: "Appointment rescheduled",
  booking_detail_reschedule_success_body:
    "Your new appointment time has been confirmed.",
  booking_detail_reschedule_error_title: "Unable to reschedule",
  booking_detail_reschedule_error_body:
    "That time is no longer available. Please choose another.",
  booking_detail_calendar_permission_title: "Calendar permission needed",
  booking_detail_calendar_permission_body:
    "Allow calendar access to save this appointment.",
  booking_detail_calendar_success_title: "Added to calendar",
  booking_detail_calendar_success_body:
    "Your appointment reminder has been saved.",
  booking_detail_calendar_error_title: "Calendar unavailable",
  booking_detail_calendar_error_body:
    "We could not save this appointment to your calendar.",
  booking_rating_action: "Give rating",
  booking_rating_title: "Rate your appointment",
  booking_rating_step: "Step {{current}} of 2",
  booking_rating_store_prompt: "How was your experience with {{name}}?",
  booking_rating_worker_prompt: "How was your experience with {{name}}?",
  booking_rating_review_label: "Write a review",
  booking_rating_optional: "Optional",
  booking_rating_review_placeholder: "Share more about your experience",
  booking_rating_next: "Next: rate professional",
  booking_rating_submit: "Submit rating",
  booking_rating_success_title: "Thank you for your rating",
  booking_rating_success_body:
    "Your feedback for the store and professional has been submitted.",
  booking_rating_error_title: "Unable to submit rating",
  booking_rating_error_body: "Please try again in a moment.",
  single_vendor_label: "Single Vendor",
  single_vendor_home_subtitle: "Book services from your trusted provider",
  single_vendor_services_title: "Services",
  single_vendor_search_title: "Search services",
  single_vendor_search_placeholder: "Search services",
  single_vendor_services_empty: "No services are available right now.",
  single_vendor_load_error: "Unable to load services right now.",
  single_vendor_home_special_title: "Book your next appointment",
  single_vendor_home_special_body:
    "Explore services, offers, and available appointments from your trusted provider.",
  single_vendor_home_bookings_cta: "My bookings",
  single_vendor_service_types_title: "Service Types",
  single_vendor_top_services_title: "Top Services",
  single_vendor_category_services_title: "Services by Category",
  single_vendor_deals_title: "Deals",
  single_vendor_order_again_title: "Order Again",
  single_vendor_see_all: "See all",
  single_vendor_section_empty_title: "Nothing here yet",
  single_vendor_section_empty_message:
    "New services and offers will appear here when they become available.",
  multi_vendor_label: "Multi Vendor",
  chain_label: "Chain",
  mode_selector_title: "How would you like to book?",
  mode_selector_subtitle:
    "Choose a booking mode to find the right service provider.",
  mode_selector_back_label: "Back to Super App home",
  single_vendor_mode_description:
    "Book directly with the platform's selected provider.",
  multi_vendor_mode_description:
    "Browse and compare services from multiple providers.",
  chain_mode_description:
    "Choose a branch from the configured provider chain.",
  chain_branches_title: "Choose a branch",
  chain_branches_subtitle: "Select a nearby branch to view services and availability",
  chain_search_placeholder: "Search branches",
  chain_branches_empty: "No chain branches are available in this area.",
  chain_branches_load_error: "Unable to load chain branches right now.",
  chain_home_special_title: "Book across your favourite chain",
  chain_home_special_body:
    "Choose a nearby branch and find the right appointment for you.",
  chain_home_bookings_cta: "My bookings",
  chain_home_branches_title: "Nearby branches",
  chain_home_top_services_title: "Popular services",
  chain_home_order_again_title: "Order again",
  chain_home_see_all: "See all",
  chain_home_empty_title: "Nothing here yet",
  chain_home_top_services_empty:
    "Popular services from this chain will appear here.",
  chain_home_order_again_empty:
    "Services you previously booked from this chain will appear here.",
  tab_home: "Home",
  tab_search: "Search",
  search_placeholder: "Search",
  searching_near: "Searching near",
  search_location_fallback: "Select a service location",
  search_results_title: "Providers near you",
  search_empty_title: "Nothing here yet",
  search_empty_message: "Try another service, category, or provider name.",
  search_error_message:
    "We could not load search results right now. Please try again.",
  tab_bookings: "Bookings",
  tab_profile: "Profile",
  screen_details: "Details",
  mode_screen_title: "{{mode}} {{screen}}",
  mode_screen_subtitle: "{{mode}} workspace",
  mode_screen_body:
    "This is the {{screen}} placeholder for {{mode}} appointments.",
  mode_screen_note:
    "Appointments structure is ready for feature-specific screens, hooks, and data layers.",
  multi_vendor_home_hero_title: "What are you looking for today?",
  multi_vendor_home_hero_body:
    "Discover appointment providers, compare categories, and jump back into repeat bookings from one polished home.",
  multi_vendor_home_special_title: "Today's Special",
  multi_vendor_home_special_body:
    "Get a discount for every service order. Valid for today only.",
  multi_vendor_home_search_prompt: "Search providers, categories, and services",
  multi_vendor_home_explore_cta: "Explore now",
  multi_vendor_home_bookings_cta: "My bookings",
  multi_vendor_home_stat_categories: "Categories",
  multi_vendor_home_stat_providers: "Providers",
  multi_vendor_home_stat_repeat: "Repeat items",
  multi_vendor_home_next_step_title: "Next we can build the listing sections",
  multi_vendor_home_next_step_body:
    "This appointments home is now powered by general-bookings discovery data, so we can keep layering in richer search and booking flows from here.",
  multi_vendor_shop_types_title: "Appointments",
  multi_vendor_top_brands_title: "Top Brands",
  multi_vendor_nearby_store_title: "Nearby your Location",
  multi_vendor_order_again_title: "Order Again",
  multi_vendor_most_popular_title: "Most Popular",
  multi_vendor_see_all: "See all",
  multi_vendor_home_section_empty_title: "Nothing here yet",
  multi_vendor_top_brands_empty:
    "Featured providers will appear here once they are available.",
  multi_vendor_location_stores_empty:
    "Add or select an address to discover providers available near you.",
  multi_vendor_home_section_empty_order_again:
    "Your recently booked services will appear here so you can book them again quickly.",
  multi_vendor_home_section_empty_most_popular:
    "Popular services will appear here after customers complete their bookings.",
  see_all_search_placeholder: "Search categories, brands, and providers",
  see_all_categories_subtitle:
    "Browse all appointment categories in one consistent list view.",
  see_all_shop_type_categories_subtitle:
    "Explore all service categories available inside this appointment type.",
  see_all_top_brands_subtitle:
    "Explore every featured provider brand available for appointments.",
  see_all_nearby_subtitle:
    "Find nearby appointment providers using the same shared listing layout.",
  see_all_most_popular_subtitle:
    "Review the most popular appointment services in one place.",
  see_all_order_again_subtitle:
    "Quickly revisit services from your completed appointments.",
  see_all_error_message:
    "We could not load this section right now. Pull to refresh and try again.",
  see_all_empty_message: "No matching items were found for this section yet.",
  wallet_balance_label: "Wallet balance",
  wallet_cards_title: "Cards",
  wallet_add_card: "Add debit/credit card",
  wallet_recent_transactions: "Recent Transactions",
  wallet_transactions_empty_title: "No transactions yet",
  wallet_transactions_empty_description: "Your wallet activity will appear here after a payment or refund.",
  wallet_see_all: "See all",
  wallet_add_card_title: "Add card",
  wallet_name_on_card: "Name on card",
  wallet_name_placeholder: "Add card holder full name",
  wallet_card_number_label: "Card number",
  wallet_pay_securely: "Pay securely with Stripe",
  wallet_save_card: "Save",
  wallet_no_saved_cards: "No saved cards yet",
  wallet_add_card_error: "Unable to save card",
  wallet_stripe_publishable_key_missing: "Stripe publishable key is missing.",
  wallet_card_incomplete: "Please complete card details.",
  wallet_card_saved_success_title: "Card saved",
  wallet_card_saved_success_message: "Your card was added successfully.",
};

export default en;
