const fr = {
  label: "Rendez-vous",
  description: "Gérez vos réservations.",
  header_title: "Rendez-vous",
  header_subtitle: "Gérez vos réservations",
  home_body: "Planifiez et gérez des rendez-vous.",
  details_title: "Détails du Rendez-vous",
  details_body: "Détails du rendez-vous et rappels.",
  details_meta_category: "Catégorie",
  details_meta_distance: "Distance",
  details_meta_rating: "Note",
  details_meta_offer: "Offre",
  details_meta_hours_fallback: "Fermé aujourd'hui",
  details_closed_badge: "Fermé",
  details_closed_notice:
    "Ce centre est actuellement fermé, la commande est donc temporairement indisponible.",
  details_closed_overlay_title: "Centre fermé",
  details_closed_overlay_body:
    "La commande reste désactivée jusqu’à la réouverture de ce centre.",
  details_action_back: "Retour",
  details_action_info: "Informations du centre",
  details_action_share: "Partager le centre",
  details_about_title: "À propos",
  details_close: "Fermer",
  details_open_until: "Ouvert jusqu’à {{time}}",
  details_timing_closed: "Fermé",
  details_team_role_fallback: "Équipe",
  details_service_meta_fallback: "1 h",
  details_search_placeholder: "Rechercher des services",
  details_services_title: "Tous les services proposés",
  details_services_empty:
    "Aucun service ne correspond encore à cette sélection.",
  details_store_missing: "Impossible d'ouvrir ce prestataire de rendez-vous.",
  details_load_error:
    "Impossible de charger ce prestataire de rendez-vous pour le moment.",
  details_tab_all: "Tous",
  details_get_in_touch: "Prendre contact",
  details_our_services: "Nos services",
  details_team: "Équipe",
  details_reviews: "Avis",
  details_opening_times: "Heures d'ouverture",
  details_additional_info: "Informations supplémentaires",
  details_book_now: "Réserver",
  details_book_now_short: "Réserver",
  details_services_available: "{{count}} services disponibles",
  details_reviews_count: "{{count}} avis",
  details_rating_with_count: "{{rating}} ({{count}} avis)",
  details_get_directions: "Itinéraire",
  details_team_empty:
    "Les informations de l'équipe ne sont pas encore disponibles.",
  details_reviews_empty: "Il n'y a pas encore d'avis.",
  details_info_phone: "Assistance téléphonique disponible",
  details_info_email: "Contact par e-mail disponible",
  details_info_online_booking: "Réservation en ligne disponible",
  details_info_available_today: "Rendez-vous disponibles aujourd'hui",
  team_screen_title: "Équipe",
  team_any_professional: "N’importe quel professionnel",
  team_any_professional_subtitle: "Pour une disponibilité maximale",
  team_select: "Sélectionner",
  team_select_info_title: "Sélection de l'équipe",
  team_select_info_body:
    "La sélection du travailleur sera bientôt reliée au parcours de réservation.",
  team_schedule_date_time_confirm: "Choisir la date et l'heure",
  team_schedule_picker_confirm: "Confirmer la date et l'heure",
  team_schedule_available_slots_title: "Choisir une heure disponible",
  team_schedule_available_times: "Heures disponibles",
  team_schedule_today: "Aujourd'hui",
  team_schedule_loading_slots: "Chargement des heures disponibles…",
  team_schedule_no_slots:
    "Aucune heure n'est disponible à cette date. Choisissez une autre date.",
  team_schedule_slot_taken_title: "Cette heure n'est plus disponible",
  team_schedule_slot_taken_body:
    "Les disponibilités ont été actualisées. Sélectionnez une autre heure.",
  team_schedule_unavailable_title: "Créneau indisponible",
  team_schedule_unavailable_body:
    "Veuillez choisir une autre date ou heure pour ce rendez-vous.",
  team_schedule_error_title: "Impossible de poursuivre la réservation",
  team_schedule_error_body:
    "Nous ne pouvons pas charger les disponibilités pour le moment.",
  services_screen_title: "Services",
  services_variants_label: "Variantes disponibles",
  services_select_info_body:
    "La personnalisation du service sera bientôt reliée au parcours de réservation.",
  services_selection_info_title: "Sélection du service",
  services_selection_info_body: "Sélectionnez un service pour continuer.",
  services_clear_selection: "Effacer les services sélectionnés",
  services_continue: "Continuer",
  services_selected_count_one: "{{count}} service",
  services_selected_count_other: "{{count}} services",
  cart_store_conflict_title: "Remplacer votre panier actuel ?",
  cart_store_conflict_body:
    "Votre panier contient des services d’un autre établissement. Les supprimer et ajouter les services de {{store}} ?",
  cart_store_conflict_keep: "Garder le panier actuel",
  cart_store_conflict_replace: "Remplacer le panier",
  cart_save_error_title: "Impossible d’enregistrer le panier",
  cart_save_error_body: "Veuillez réessayer d’ajouter ces services.",
  review_confirm_title: "Vérifier et confirmer",
  review_confirm_professional_title: "Professionnel",
  review_confirm_payment_title: "Paiement",
  review_confirm_payment_cash: "Payer après le service",
  review_confirm_payment_stripe: "Carte",
  review_confirm_payment_change_hint: "Appuyez pour modifier",
  review_confirm_discount_title: "Code promo",
  review_confirm_discount_hint: "Appuyez pour continuer",
  review_confirm_payment_missing_title: "Paiement indisponible",
  review_confirm_payment_missing_body:
    "Aucun mode de paiement pris en charge n’est disponible pour cette réservation.",
  review_confirm_notes_title: "Notes",
  review_confirm_notes_optional: "Optionnel",
  review_confirm_notes_placeholder:
    "Ajoutez des instructions pour ce rendez-vous",
  review_confirm_cancellation_title: "Politique d'annulation",
  review_confirm_total_title: "Total",
  review_confirm_total_subtitle: "Taxes incluses (si applicable)",
  review_confirm_any_professional: "N’importe quel professionnel",
  review_confirm_footer_cta: "Confirmer",
  review_confirm_popup_title: "Politique d'annulation",
  review_confirm_popup_accept: "Accepter et confirmer",
  review_confirm_appointment_confirmed: "Rendez-vous confirmé",
  review_confirm_success_body:
    "Votre réservation avec {{storeName}} est confirmée. ID de commande : {{orderId}}.",
  review_confirm_success_bookings: "Voir les réservations",
  review_confirm_success_home: "Retour à l'accueil",
  review_confirm_place_order_error_title:
    "Impossible de confirmer la réservation",
  review_confirm_place_order_error_body: "Veuillez réessayer dans un instant.",
  review_confirm_discount_selected:
    "{{code}} sélectionné. L’éligibilité sera vérifiée lors de la confirmation.",
  review_confirm_discount_refreshing:
    "Mise à jour du total de votre rendez-vous…",
  review_confirm_discount_applied:
    "{{code}} appliqué · Vous économisez {{value}}",
  coupons_title: "Coupons",
  coupons_description:
    "Saisissez un code promo ou choisissez une offre pour votre rendez-vous.",
  coupons_placeholder: "Saisir un code promo",
  coupons_apply: "Appliquer le coupon",
  coupons_off: "DE RÉDUCTION",
  coupons_minimum: "Réservation minimale : {{value}} $",
  coupons_valid_until: "Valable jusqu’au {{date}}",
  coupons_use: "Utiliser le coupon",
  coupons_deactivate: "Désactiver",
  coupons_applied_title: "Coupon appliqué",
  coupons_applied_body:
    "Le total de votre rendez-vous sera mis à jour au paiement.",
  coupons_removed_title: "Coupon supprimé",
  coupons_removed_body: "Le coupon n’est plus appliqué.",
  coupons_error_title: "Coupon indisponible",
  coupons_error_body: "Veuillez réessayer dans un instant.",
  coupons_invalid_code: "Saisissez un code promo actif valide.",
  coupons_load_error:
    "Impossible de charger les coupons. Tirez pour réessayer.",
  coupons_empty_title: "Aucun coupon disponible",
  coupons_empty_body: "Les nouvelles offres de rendez-vous apparaîtront ici.",
  cart_title: "Panier",
  cart_clear_action: "Vider le panier",
  cart_empty_title: "Rien ici pour le moment",
  cart_empty_body:
    "Ajoutez des services à votre panier pour pouvoir revenir et poursuivre la réservation à tout moment.",
  cart_empty_action: "Sélectionner un service",
  favourites_title: "Vos Favoris",
  favourites_empty_title: "Aucun favori pour l'instant",
  favourites_empty_subtitle: "Les magasins que vous aimez apparaîtront ici.",
  favourites_error:
    "Impossible de charger les favoris. Tirez vers le bas pour réessayer.",
  favourites_toggle_added: "Ajouté aux favoris",
  favourites_toggle_removed: "Retiré des favoris",
  favourites_toggle_error: "Échec de la mise à jour des favoris",
  favourites_services_title: "Services favoris",
  favourites_services_empty_title: "Aucun service favori",
  favourites_services_empty_message:
    "Les services favoris de ce prestataire apparaîtront ici.",
  favourites_service_added: "Service ajouté aux favoris",
  favourites_service_removed: "Service retiré des favoris",
  bookings_title: "Rendez-vous",
  bookings_my_appointments_title: "Mes rendez-vous",
  bookings_upcoming_title: "À venir",
  bookings_completed_title: "Terminés",
  bookings_cancelled_title: "Annulés",
  bookings_past_title: "Passés",
  bookings_empty_title: "Aucun rendez-vous trouvé",
  bookings_empty_subtitle:
    "Vos rendez-vous à venir et passés apparaîtront une fois une réservation effectuée.",
  bookings_empty_action: "Voir les prestataires",
  bookings_upcoming_empty_title: "Aucun rendez-vous à venir",
  bookings_upcoming_empty_subtitle:
    "Votre prochaine réservation apparaîtra ici une fois confirmée.",
  bookings_completed_empty_title: "Aucun rendez-vous terminé",
  bookings_completed_empty_subtitle:
    "Les rendez-vous terminés apparaîtront ici.",
  bookings_cancelled_empty_title: "Aucun rendez-vous annulé",
  bookings_cancelled_empty_subtitle:
    "Les rendez-vous annulés apparaîtront ici.",
  bookings_past_summary: "Service de rendez-vous",
  bookings_error_title: "Impossible de charger les rendez-vous",
  bookings_error_subtitle: "Actualisez la page ou réessayez dans un instant.",
  bookings_retry: "Réessayer",
  bookings_book_again: "Réserver à nouveau",
  bookings_scheduled_badge: "Planifié",
  bookings_meta_items_one: "{{count}} article",
  bookings_meta_items_other: "{{count}} articles",
  bookings_meta_time_pending: "Rendez-vous planifié",
  bookings_get_directions: "Obtenir l'itinéraire",
  bookings_date_title: "Date du rendez-vous",
  bookings_location_unavailable: "La localisation du magasin est indisponible.",
  booking_detail_error_title: "Impossible de charger ce rendez-vous",
  booking_detail_duration: "Durée : {{duration}}",
  booking_detail_add_calendar: "Ajouter au calendrier",
  booking_detail_add_calendar_subtitle: "Créer un rappel",
  booking_detail_getting_there: "S’y rendre",
  booking_detail_manage: "Gérer le rendez-vous",
  booking_detail_manage_subtitle: "Choisissez une nouvelle date et heure",
  booking_detail_cancel: "Annuler la réservation",
  booking_detail_cancel_available:
    "Disponible jusqu’à 2 heures avant le rendez-vous",
  booking_detail_cancel_unavailable:
    "L’annulation est indisponible dans les 2 heures précédant le rendez-vous",
  booking_detail_cancel_confirm_title: "Annuler cette réservation ?",
  booking_detail_cancel_confirm_body: "Cette action est irréversible.",
  booking_detail_cancel_confirm_action: "Annuler la réservation",
  booking_detail_cancel_success_title: "Réservation annulée",
  booking_detail_cancel_success_body: "Votre rendez-vous a été annulé.",
  booking_detail_cancel_error_title: "Impossible d’annuler la réservation",
  booking_detail_cancel_error_body:
    "Ce rendez-vous se trouve peut-être dans le délai limite de deux heures.",
  booking_detail_manage_unavailable:
    "Les modifications ne sont pas encore disponibles. Contactez le prestataire.",
  booking_detail_venue: "Détails du lieu",
  booking_detail_overview: "Aperçu",
  booking_detail_total: "Total",
  booking_detail_service_fee: "Frais de service",
  booking_detail_reschedule_now: "Reprogrammer maintenant",
  booking_detail_reschedule_success_title: "Rendez-vous reprogrammé",
  booking_detail_reschedule_success_body:
    "La nouvelle heure de votre rendez-vous est confirmée.",
  booking_detail_reschedule_error_title: "Reprogrammation impossible",
  booking_detail_reschedule_error_body:
    "Cette heure n’est plus disponible. Choisissez-en une autre.",
  booking_detail_calendar_permission_title:
    "Autorisation du calendrier requise",
  booking_detail_calendar_permission_body:
    "Autorisez l’accès au calendrier pour enregistrer ce rendez-vous.",
  booking_detail_calendar_success_title: "Ajouté au calendrier",
  booking_detail_calendar_success_body:
    "Le rappel de votre rendez-vous a été enregistré.",
  booking_detail_calendar_error_title: "Calendrier indisponible",
  booking_detail_calendar_error_body:
    "Impossible d’enregistrer ce rendez-vous dans votre calendrier.",
  booking_rating_action: "Donner une note",
  booking_rating_title: "Évaluer votre rendez-vous",
  booking_rating_step: "Étape {{current}} sur 2",
  booking_rating_store_prompt:
    "Comment s’est passée votre expérience avec {{name}} ?",
  booking_rating_worker_prompt:
    "Comment s’est passée votre expérience avec {{name}} ?",
  booking_rating_review_label: "Écrire un avis",
  booking_rating_optional: "Facultatif",
  booking_rating_review_placeholder: "Partagez votre expérience",
  booking_rating_next: "Suivant : évaluer le professionnel",
  booking_rating_submit: "Envoyer la note",
  booking_rating_success_title: "Merci pour votre note",
  booking_rating_success_body:
    "Votre avis sur le magasin et le professionnel a été envoyé.",
  booking_rating_error_title: "Impossible d’envoyer la note",
  booking_rating_error_body: "Veuillez réessayer dans un instant.",
  single_vendor_label: "Vendeur unique",
  single_vendor_home_subtitle: "Réservez auprès de votre prestataire de confiance",
  single_vendor_services_title: "Services",
  single_vendor_search_title: "Rechercher des services",
  single_vendor_search_placeholder: "Rechercher des services",
  single_vendor_services_empty: "Aucun service n’est disponible pour le moment.",
  single_vendor_load_error: "Impossible de charger les services pour le moment.",
  single_vendor_home_special_title: "Réservez votre prochain rendez-vous",
  single_vendor_home_special_body:
    "Découvrez les services, les offres et les rendez-vous disponibles auprès de votre prestataire.",
  single_vendor_home_bookings_cta: "Mes réservations",
  single_vendor_service_types_title: "Types de services",
  single_vendor_top_services_title: "Services populaires",
  single_vendor_category_services_title: "Services par catégorie",
  single_vendor_deals_title: "Offres",
  single_vendor_order_again_title: "Réserver à nouveau",
  single_vendor_see_all: "Tout voir",
  single_vendor_section_empty_title: "Rien pour le moment",
  single_vendor_section_empty_message:
    "Les nouveaux services et offres apparaîtront ici dès qu’ils seront disponibles.",
  multi_vendor_label: "Multi-vendeur",
  chain_label: "Chaîne",
  mode_selector_title: "Comment souhaitez-vous réserver ?",
  mode_selector_subtitle:
    "Choisissez un mode de réservation pour trouver le bon prestataire.",
  mode_selector_back_label: "Retour à l’accueil de la Super App",
  single_vendor_mode_description:
    "Réservez directement auprès du prestataire sélectionné par la plateforme.",
  multi_vendor_mode_description:
    "Parcourez et comparez les services de plusieurs prestataires.",
  chain_mode_description:
    "Choisissez une agence dans la chaîne de prestataires configurée.",
  chain_branches_title: "Choisissez une agence",
  chain_branches_subtitle: "Sélectionnez une agence proche pour voir les services et disponibilités",
  chain_search_placeholder: "Rechercher des agences",
  chain_branches_empty: "Aucune agence de la chaîne n’est disponible dans cette zone.",
  chain_branches_load_error: "Impossible de charger les agences pour le moment.",
  chain_home_special_title: "Réservez dans votre chaîne préférée",
  chain_home_special_body:
    "Choisissez une agence proche et trouvez le rendez-vous qui vous convient.",
  chain_home_bookings_cta: "Mes réservations",
  chain_home_branches_title: "Agences à proximité",
  chain_home_top_services_title: "Services populaires",
  chain_home_order_again_title: "Réserver à nouveau",
  chain_home_see_all: "Voir tout",
  chain_home_empty_title: "Rien pour le moment",
  chain_home_top_services_empty:
    "Les services populaires de cette chaîne apparaîtront ici.",
  chain_home_order_again_empty:
    "Les services déjà réservés dans cette chaîne apparaîtront ici.",
  chain_favourites_title: "Agences favorites",
  chain_favourites_empty_title: "Aucune agence favorite",
  chain_favourites_empty_message:
    "Les agences enregistrées de cette chaîne apparaîtront ici.",
  tab_home: "Accueil",
  tab_search: "Recherche",
  search_placeholder: "Rechercher",
  searching_near: "Recherche près de",
  search_location_fallback: "Sélectionner un lieu de service",
  search_results_title: "Prestataires près de chez vous",
  search_empty_title: "Rien ici pour le moment",
  search_empty_message:
    "Essayez un autre service, une autre catégorie ou un autre prestataire.",
  search_error_message:
    "Impossible de charger les résultats pour le moment. Veuillez réessayer.",
  tab_bookings: "Réservations",
  tab_profile: "Profil",
  screen_details: "Détails",
  mode_screen_title: "{{mode}} {{screen}}",
  mode_screen_subtitle: "Espace {{mode}}",
  mode_screen_body: "Ceci est l’écran {{screen}} de réservation pour {{mode}}.",
  mode_screen_note:
    "La structure des rendez-vous est prête pour les écrans, hooks et couches de données spécifiques.",
  multi_vendor_home_hero_title: "Que recherchez-vous aujourd'hui ?",
  multi_vendor_home_hero_body:
    "Découvrez des prestataires de rendez-vous, comparez les catégories et relancez rapidement vos réservations habituelles.",
  multi_vendor_home_special_title: "L'offre du jour",
  multi_vendor_home_special_body:
    "Obtenez une remise sur chaque réservation de service. Valable aujourd’hui seulement.",
  multi_vendor_home_search_prompt:
    "Rechercher des prestataires, catégories et services",
  multi_vendor_home_explore_cta: "Explorer",
  multi_vendor_home_bookings_cta: "Mes réservations",
  multi_vendor_home_stat_categories: "Catégories",
  multi_vendor_home_stat_providers: "Prestataires",
  multi_vendor_home_stat_repeat: "À répéter",
  multi_vendor_home_next_step_title:
    "Nous pouvons maintenant créer les sections de listing",
  multi_vendor_home_next_step_body:
    "Cet accueil de rendez-vous utilise maintenant les données discovery de general-bookings, ce qui permet d'ajouter ensuite des parcours de recherche et de réservation plus riches.",
  multi_vendor_shop_types_title: "Catégories de rendez-vous",
  multi_vendor_top_brands_title: "Top marques",
  multi_vendor_nearby_store_title: "Près de votre zone",
  multi_vendor_order_again_title: "Réserver à nouveau",
  multi_vendor_most_popular_title: "Les plus populaires",
  multi_vendor_see_all: "Voir tout",
  multi_vendor_home_section_empty_title: "Rien pour le moment",
  multi_vendor_top_brands_empty:
    "Les prestataires mis en avant apparaîtront ici lorsqu’ils seront disponibles.",
  multi_vendor_location_stores_empty:
    "Ajoutez ou sélectionnez une adresse pour découvrir les prestataires proches de vous.",
  multi_vendor_home_section_empty_order_again:
    "Vos services réservés récemment apparaîtront ici pour vous permettre de les réserver à nouveau rapidement.",
  multi_vendor_home_section_empty_most_popular:
    "Les services populaires apparaîtront ici après les réservations terminées par les clients.",
  see_all_search_placeholder:
    "Rechercher des catégories, marques et prestataires",
  see_all_categories_subtitle:
    "Parcourez toutes les catégories de rendez-vous dans une vue cohérente.",
  see_all_shop_type_categories_subtitle:
    "Explorez toutes les catégories de service disponibles dans ce type de rendez-vous.",
  see_all_top_brands_subtitle:
    "Explorez toutes les marques de prestataires mises en avant.",
  see_all_nearby_subtitle:
    "Trouvez les prestataires proches avec la même interface partagée.",
  see_all_most_popular_subtitle:
    "Consultez les services de rendez-vous les plus populaires au même endroit.",
  see_all_order_again_subtitle:
    "Retrouvez rapidement les services de vos rendez-vous terminés.",
  see_all_error_message:
    "Impossible de charger cette section pour le moment. Actualisez puis réessayez.",
  see_all_empty_message:
    "Aucun élément correspondant n’a encore été trouvé pour cette section.",
  wallet_balance_label: "Solde du portefeuille",
  wallet_cards_title: "Cartes",
  wallet_add_card: "Ajouter une carte de débit/crédit",
  wallet_recent_transactions: "Transactions récentes",
  wallet_transactions_empty_title: "Aucune transaction pour le moment",
  wallet_transactions_empty_description: "L’activité de votre portefeuille apparaîtra ici après un paiement ou un remboursement.",
  wallet_see_all: "Voir tout",
  wallet_add_card_title: "Ajouter une carte",
  wallet_name_on_card: "Nom sur la carte",
  wallet_name_placeholder: "Nom complet du titulaire",
  wallet_card_number_label: "Numéro de carte",
  wallet_pay_securely: "Paiement sécurisé avec Stripe",
  wallet_save_card: "Enregistrer",
  wallet_no_saved_cards: "Aucune carte enregistrée",
  wallet_add_card_error: "Impossible d’enregistrer la carte",
  wallet_stripe_publishable_key_missing: "La clé publique Stripe est manquante.",
  wallet_card_incomplete: "Veuillez compléter les informations de la carte.",
  wallet_card_saved_success_title: "Carte enregistrée",
  wallet_card_saved_success_message: "Votre carte a été ajoutée.",
};

export default fr;
