const en = {
  app_name: 'Super Customer App',
  greeting: 'Good Morning 👋',
  home_question: 'What are you looking for Today?',
  home_title: 'Home',
  home_subtitle: 'How can I help you today?',
  special_offer_label: '10% off',
  special_title: "Today's Special",
  special_description: 'Get a discount for every service order!',
  special_note: 'Only valid for today!',
  special_percent: '30%',
  services_title: 'Our Services',
  open_button: 'Open',
  service_type_title: 'Service Type',
  recommended_title: 'Recommended For You',
  recommended_name: 'Premium Cleaning',
  recommended_name_secondary: 'Fast Electrician',
  recommended_rating: '4.8 | 1,500+ reviews',
  service_deliveries: 'Deliveries',
  service_home_visit: 'Home-Visit Appointment',
  service_general_appointment: 'General Appointment',
  service_ride_sharing: 'Ride Sharing',
  recommended_price: '${{price}}/hr',
  recommended_reviews: '{{count}}+ reviews',
  splash_title: 'Food Delivery',
  loading: 'Loading...',
  splash_progress: '{{value}}%',
  developer_mode: 'Dev Mode',
  developer_mode_subtitle: 'System tools & diagnostics',
  developer_mode_welcome: 'Welcome to Developer Mode. Additional diagnostic tools will be available here soon.',
  driver_profile_button: 'Driver profile',
  dev_auth_title: 'Auth Sandbox',
  dev_auth_description: 'Temporary signup + session tools for development.',
  dev_auth_mode_signup: 'Signup',
  dev_auth_mode_login: 'Login',
  dev_auth_phone_label: 'Phone',
  dev_auth_phone_placeholder: '+923001234567',
  dev_auth_otp_label: 'OTP',
  dev_auth_otp_placeholder: '123456',
  dev_auth_name_label: 'Name',
  dev_auth_name_placeholder: 'John Doe',
  dev_auth_password_label: 'Password',
  dev_auth_password_placeholder: 'password123',
  dev_auth_push_token_label: 'Device Push Token',
  dev_auth_push_token_placeholder: 'fcm-token-here',
  dev_auth_referral_label: 'Referral Code',
  dev_auth_referral_placeholder: 'REF123',
  dev_auth_send_otp_button: 'Send OTP',
  dev_auth_send_login_otp_button: 'Send Login OTP',
  dev_auth_verify_button: 'Verify OTP & Create User',
  dev_auth_login_button: 'Verify OTP & Login',
  dev_auth_logout_button: 'Logout',
  dev_auth_status_label: 'Session Status',
  dev_auth_status_user: 'User: {{name}}',
  dev_auth_status_working: 'Working on request...',
  dev_auth_status_otp_sent: 'OTP sent. Verify to complete signup.',
  dev_auth_status_verified: 'Signup verified. Session stored.',
  dev_auth_status_failed: 'Request failed. Check the error below.',
  dev_auth_status_signed_in: 'Session active.',
  dev_auth_status_signed_out: 'No active session.',
  login_to_continue: 'Login to Continue',
  login_to_continue_desc: 'Please log in to save your delivery details and ensure a smooth, secure checkout experience.',
  continue_with_phone: 'Continue with Phone',
  continue_with_google: 'Continue with Google',
  continue_with_email: 'Continue with Email',
  or: 'or',
  dont_have_an_account: 'Don’t have an account?',
  signup: 'Sign Up',
  continue: 'Continue',
  enter_your_phone: 'Log in easily by entering your phone!',
  login_desc: 'We’ll check if you have an account',
  verify_your_phone_number: 'Verify Your Phone Number',
  verify_otp: 'Verify OTP',
  enter_otp_sent_to: 'Enter OTP sent to',
  didnt_receive_the_code: 'Didn’t receive the code?',
  resend_in: 'Resend in',
  try_another_way: 'Try another way',
  resend: 'Resend',
  incorrect_code: 'The code you entered is incorrect.',
  get_started: 'Let’s get you started',
  get_started_desc: 'First, let create your account',
  create_account: 'Create account',
  name: "Name",
  email: "Email",
  password: "Password",
  sms_verification: "Send code by SMS",
  call_verification: "Send code by Call",
  email_verification: "Send code by Mail",
  too_many_attempts: "Too many attempts",
  too_many_attempts_desc: "We’ve temporarily locked further attempts to protect your account. Try again in 5 minutes.",
  ok: "Ok",
  enter_your_email: 'Log in easily by entering your email!',
  enter_your_password: 'Enter your password',
  email_already_exist: 'Your email already exist.',
  remember_me: 'Remember me',
  forget_password: 'Forget Password?',
  enter_correct_password: 'Please enter the correct password.',
  forget_password_desc: 'Enter your email and we’ll send an OTP to reset your password.',
  create_new_password: 'Create your new password',
  create_password_desc: 'Set a new password and confirm it.',
  enter_new_password: 'Enter new passsword',
  confirm_new_password: 'Confirm new passsword',
  set_new_password: 'Set new password',
  verify_your_email: 'Verify Your Email',
  enter_strong_password: 'Please enter strong password.',
  password_not_matched: 'Make sure your passwords match',
  location_popup_title: 'Location Access',
  location_popup_description:
    'Use device location to show nearby stores, delivery availability, and relevant offers.',
  location_popup_denied_title: 'Location Permission Denied',
  location_popup_denied_description:
    'Location access is still off. Allow it to show nearby stores and accurate delivery availability.',
  location_popup_blocked_title: 'Enable Location in Settings',
  location_popup_blocked_description:
    'Location access is turned off for this app. Open settings to allow location access on your device.',
  location_popup_enable: 'Enable Location',
  location_popup_try_again: 'Try Again',
  location_popup_open_settings: 'Open Settings',
  location_popup_later: 'Maybe Later'
};

export default en;
