const fr = {
  app_name: 'Application Super Client',
  greeting: 'Bonjour 👋',
  home_question: 'Que recherchez-vous aujourd’hui ?',
  home_title: 'Accueil',
  home_subtitle: 'Comment puis-je vous aider aujourd\'hui ?',
  special_offer_label: '10% de réduction',
  special_title: 'Offre du jour',
  special_description: 'Obtenez une réduction pour chaque commande de service !',
  special_note: 'Valable uniquement aujourd’hui !',
  special_percent: '30%',
  services_title: 'Nos Services',
  open_button: 'Ouvrir',
  service_type_title: 'Type de Service',
  recommended_title: 'Recommandé Pour Vous',
  recommended_name: 'Nettoyage Premium',
  recommended_name_secondary: 'Électricien Express',
  recommended_rating: '4,8 | 1 500+ avis',
  service_deliveries: 'Livraisons',
  service_home_visit: 'Rendez-vous à Domicile',
  service_general_appointment: 'Rendez-vous Général',
  service_ride_sharing: 'Covoiturage',
  recommended_price: '${{price}}/h',
  recommended_reviews: '{{count}}+ avis',
  splash_title: 'Livraison de Nourriture',
  loading: 'Chargement...',
  splash_progress: '{{value}}%',
  developer_mode: 'Dev Mode',
  developer_mode_subtitle: 'Outils système et diagnostics',
  developer_mode_welcome: 'Bienvenue en mode développeur. D’autres outils de diagnostic seront bientôt disponibles.',
  driver_profile_button: 'Profil conducteur',
  auth_flow_button: 'Parcours auth',
  rider_chat_button: 'Chat livreur',
  dev_auth_title: 'Espace Auth',
  dev_auth_description: 'Outils temporaires pour inscription et session.',
  dev_auth_mode_signup: 'Inscription',
  dev_auth_mode_login: 'Connexion',
  dev_auth_phone_label: 'Téléphone',
  dev_auth_phone_placeholder: '+923001234567',
  dev_auth_otp_label: 'OTP',
  dev_auth_otp_placeholder: '123456',
  dev_auth_name_label: 'Nom',
  dev_auth_name_placeholder: 'John Doe',
  dev_auth_password_label: 'Mot de passe',
  dev_auth_password_placeholder: 'password123',
  dev_auth_push_token_label: 'Jeton Push',
  dev_auth_push_token_placeholder: 'fcm-token-here',
  dev_auth_referral_label: 'Code de parrainage',
  dev_auth_referral_placeholder: 'REF123',
  dev_auth_send_otp_button: 'Envoyer OTP',
  dev_auth_send_login_otp_button: 'Envoyer OTP Connexion',
  dev_auth_verify_button: 'Vérifier OTP et créer',
  dev_auth_login_button: 'Vérifier OTP et se connecter',
  dev_auth_logout_button: 'Se déconnecter',
  dev_auth_status_label: 'Statut de session',
  dev_auth_status_user: 'Utilisateur : {{name}}',
  dev_auth_status_working: 'Traitement de la requête...',
  dev_auth_status_otp_sent: 'OTP envoyé. Vérifiez pour terminer.',
  dev_auth_status_verified: 'Inscription vérifiée. Session enregistrée.',
  dev_auth_status_failed: 'Échec de la requête. Voir l’erreur ci-dessous.',
  dev_auth_status_signed_in: 'Session active.',
  dev_auth_status_signed_out: 'Aucune session active.',
  location_popup_title: 'Accès à la localisation',
  location_popup_description:
    'Utilisez la localisation de l’appareil pour afficher les magasins proches, la disponibilité de livraison et les offres pertinentes.',
  location_popup_denied_title: 'Autorisation refusée',
  location_popup_denied_description:
    'L’accès à la localisation est toujours désactivé. Autorisez-le pour afficher les magasins proches et la disponibilité exacte de livraison.',
  location_popup_blocked_title: 'Activez la localisation dans les réglages',
  location_popup_blocked_description:
    'L’accès à la localisation est désactivé pour cette application. Ouvrez les réglages pour autoriser la localisation sur votre appareil.',
  location_popup_enable: 'Activer la localisation',
  location_popup_try_again: 'Réessayer',
  location_popup_open_settings: 'Ouvrir les réglages',
  location_popup_later: 'Plus tard',
  address_list_title: 'Mes adresses',
  address_add_title: 'Ajouter une adresse',
  address_edit_title: "Modifier l'adresse",
  address_search_placeholder: 'Rechercher une adresse',
  address_choose_on_map: 'Choisir sur la carte',
  address_recent_searches: 'Recherches récentes',
  address_no_results: 'Aucun résultat trouvé',
  address_confirm_location: "Confirmer l'emplacement",
  address_locating: 'Localisation…',
  address_selected_location: 'Emplacement sélectionné',
  address_location_name_placeholder: 'Nom du lieu (ex. Ma maison)',
  address_details_label: "Détails de l'adresse",
  address_location_type_label: 'Type de lieu',
  address_type_home: 'Domicile',
  address_type_apartment: 'Appartement',
  address_type_office: 'Bureau',
  address_type_other: 'Autre',
  address_save: "Enregistrer l'adresse",
  address_update: "Mettre à jour l'adresse",
  address_delete: 'Supprimer',
  address_delete_confirm_title: "Supprimer l'adresse",
  address_delete_confirm_message: 'Êtes-vous sûr de vouloir supprimer cette adresse ?',
  address_delete_cancel: 'Annuler',
  address_delete_confirm: 'Supprimer',
  address_save_error: "Impossible d'enregistrer l'adresse.",
  address_select_error: "Impossible de sélectionner l'adresse.",
  address_delete_error: "Impossible de supprimer l'adresse.",
  address_save_success: 'Adresse enregistrée avec succès.',
  address_update_success: 'Adresse mise à jour avec succès.',
  address_delete_success: 'Adresse supprimée avec succès.',
  address_selector_title: 'Emplacement',
  address_selector_close: "Fermer le sélecteur d'emplacement",
  address_selector_use_current_location: 'Utiliser ma position actuelle',
  address_selector_add_new: 'Ajouter une nouvelle adresse',
  offline_notice_title: 'Vous êtes hors ligne',
  offline_notice_description: 'Reconnectez-vous pour actualiser les trajets, tarifs et données en direct.',
};

export default fr;
