const fr = {
  app_name: 'Application Super Client',
  greeting: 'Bonjour 👋',
  home_question: 'Que recherchez-vous aujourd’hui ?',
  home_title: 'Accueil',
  home_subtitle: 'Comment puis-je vous aider aujourd\'hui ?',
  special_offer_label: '10% de réduction',
  special_title: 'Offre du jour',
  special_description: 'Obtenez une réduction pour chaque commande de service !',
  special_note: 'Valable uniquement aujourd’hui !',
  special_percent: '30%',
  services_title: 'Nos Services',
  open_button: 'Ouvrir',
  service_type_title: 'Type de Service',
  recommended_title: 'Recommandé Pour Vous',
  recommended_name: 'Nettoyage Premium',
  recommended_name_secondary: 'Électricien Express',
  recommended_rating: '4,8 | 1 500+ avis',
  service_deliveries: 'Livraisons',
  service_home_visit: 'Rendez-vous à Domicile',
  service_general_appointment: 'Rendez-vous Général',
  service_ride_sharing: 'Covoiturage',
  recommended_price: '${{price}}/h',
  recommended_reviews: '{{count}}+ avis',
  splash_title: 'Livraison de Nourriture',
  loading: 'Chargement...',
  splash_progress: '{{value}}%',
  developer_mode: 'Dev Mode',
  developer_mode_subtitle: 'Outils système et diagnostics',
  developer_mode_welcome: 'Bienvenue en mode développeur. D’autres outils de diagnostic seront bientôt disponibles.',
  driver_profile_button: 'Profil conducteur',
  auth_flow_button: 'Parcours auth',
  rider_chat_button: 'Chat livreur',
  dev_auth_title: 'Espace Auth',
  dev_auth_description: 'Outils temporaires pour inscription et session.',
  dev_auth_mode_signup: 'Inscription',
  dev_auth_mode_login: 'Connexion',
  dev_auth_phone_label: 'Téléphone',
  dev_auth_phone_placeholder: '+923001234567',
  dev_auth_otp_label: 'OTP',
  dev_auth_otp_placeholder: '123456',
  dev_auth_name_label: 'Nom',
  dev_auth_name_placeholder: 'John Doe',
  dev_auth_password_label: 'Mot de passe',
  dev_auth_password_placeholder: 'password123',
  dev_auth_push_token_label: 'Jeton Push',
  dev_auth_push_token_placeholder: 'fcm-token-here',
  dev_auth_referral_label: 'Code de parrainage',
  dev_auth_referral_placeholder: 'REF123',
  dev_auth_send_otp_button: 'Envoyer OTP',
  dev_auth_send_login_otp_button: 'Envoyer OTP Connexion',
  dev_auth_verify_button: 'Vérifier OTP et créer',
  dev_auth_login_button: 'Vérifier OTP et se connecter',
  dev_auth_logout_button: 'Se déconnecter',
  dev_auth_status_label: 'Statut de session',
  dev_auth_status_user: 'Utilisateur : {{name}}',
  dev_auth_status_working: 'Traitement de la requête...',
  dev_auth_status_otp_sent: 'OTP envoyé. Vérifiez pour terminer.',
  dev_auth_status_verified: 'Inscription vérifiée. Session enregistrée.',
  dev_auth_status_failed: 'Échec de la requête. Voir l’erreur ci-dessous.',
  dev_auth_status_signed_in: 'Session active.',
  dev_auth_status_signed_out: 'Aucune session active.',
  location_popup_title: 'Accès à la localisation',
  location_popup_description:
    'Utilisez la localisation de l’appareil pour afficher les magasins proches, la disponibilité de livraison et les offres pertinentes.',
  location_popup_denied_title: 'Autorisation refusée',
  location_popup_denied_description:
    'L’accès à la localisation est toujours désactivé. Autorisez-le pour afficher les magasins proches et la disponibilité exacte de livraison.',
  location_popup_blocked_title: 'Activez la localisation dans les réglages',
  location_popup_blocked_description:
    'L’accès à la localisation est désactivé pour cette application. Ouvrez les réglages pour autoriser la localisation sur votre appareil.',
  location_popup_enable: 'Activer la localisation',
  location_popup_try_again: 'Réessayer',
  location_popup_open_settings: 'Ouvrir les réglages',
  location_popup_later: 'Plus tard',
  address_list_title: 'Mes adresses',
  address_add_title: 'Ajouter une adresse',
  address_edit_title: "Modifier l'adresse",
  address_search_placeholder: 'Rechercher une adresse',
  address_choose_on_map: 'Choisir sur la carte',
  address_recent_searches: 'Recherches récentes',
  address_no_results: 'Aucun résultat trouvé',
  address_confirm_location: "Confirmer l'emplacement",
  address_locating: 'Localisation…',
  address_selected_location: 'Emplacement sélectionné',
  address_location_name_placeholder: 'Nom du lieu (ex. Ma maison)',
  address_details_label: "Détails de l'adresse",
  address_location_type_label: 'Type de lieu',
  address_type_home: 'Domicile',
  address_type_apartment: 'Appartement',
  address_type_office: 'Bureau',
  address_type_other: 'Autre',
  address_save: "Enregistrer l'adresse",
  address_update: "Mettre à jour l'adresse",
  address_delete: 'Supprimer',
  address_delete_confirm_title: "Supprimer l'adresse",
  address_delete_confirm_message: 'Êtes-vous sûr de vouloir supprimer cette adresse ?',
  address_delete_cancel: 'Annuler',
  address_delete_confirm: 'Supprimer',
  address_save_error: "Impossible d'enregistrer l'adresse.",
  address_select_error: "Impossible de sélectionner l'adresse.",
  address_delete_error: "Impossible de supprimer l'adresse.",
  address_save_success: 'Adresse enregistrée avec succès.',
  address_update_success: 'Adresse mise à jour avec succès.',
  address_delete_success: 'Adresse supprimée avec succès.',
  address_selector_title: 'Emplacement',
  address_selector_close: "Fermer le sélecteur d'emplacement",
  address_selector_use_current_location: 'Utiliser ma position actuelle',
  address_selector_add_new: 'Ajouter une nouvelle adresse',
  profile_personal_account: 'Compte personnel',
  profile_wallet_balance: 'Solde du portefeuille',
  profile_view_wallet: 'Voir le portefeuille',
  profile_menu_profile: 'Profil',
  profile_menu_notifications: 'Notifications',
  profile_menu_favorites: 'Favoris',
  profile_menu_coupons: 'Coupons',
  profile_menu_settings: 'Paramètres',
  profile_menu_support: 'Assistance',
  profile_menu_color_mode: 'Mode couleur',
  profile_menu_language: 'Langue',
  profile_menu_logout: 'Se déconnecter',
  my_profile_title: 'Mon profil',
  my_profile_edit: 'Modifier',
  my_profile_full_name: 'Nom complet',
  my_profile_date_of_birth: 'Date de naissance',
  my_profile_mobile_number: 'Numéro de téléphone',
  my_profile_email: 'E-mail',
  my_profile_my_addresses: 'Mes adresses',
  my_profile_add_address: 'Ajouter une adresse',
  my_profile_address_home: 'Domicile',
  my_profile_address_apartment: 'Appartement',
  my_profile_address_work: 'Travail',
  my_profile_address_other: 'Autre',
  photo_modal_title: 'Photo de profil',
  photo_modal_description: 'Choisissez comment mettre à jour votre photo de profil',
  photo_take_photo: 'Prendre une photo',
  photo_choose_gallery: 'Choisir dans la galerie',
  photo_cancel: 'Annuler',
  photo_permission_title: 'Autorisation requise',
  photo_permission_camera: "L'accès à la caméra est nécessaire pour prendre une photo.",
  photo_permission_gallery: "L'accès à la galerie est nécessaire pour choisir une photo.",
  photo_upload_error_title: 'Échec du téléchargement',
  photo_upload_failed: 'Impossible de mettre à jour la photo de profil.',
  edit_profile_title: 'Modifier le profil',
  edit_profile_name: 'Nom',
  edit_profile_date_of_birth: 'Date de naissance',
  edit_profile_day: 'Jour',
  edit_profile_month: 'Mois',
  edit_profile_year: 'Année',
  edit_profile_gender: 'Genre',
  edit_profile_gender_placeholder: 'Sélectionner une option',
  edit_profile_save: 'Enregistrer',
  edit_profile_success: 'Succès',
  edit_profile_success_message: 'Profil mis à jour avec succès.',
  edit_profile_error: 'Erreur',
  edit_profile_name_required: 'Le nom est requis.',
  edit_profile_failed: 'Impossible de mettre à jour le profil.',
  settings_title: 'Paramètres',
  settings_notifications: 'Paramètres de notifications',
  settings_change_password: 'Changer le mot de passe',
  settings_privacy_policy: 'Politique de confidentialité',
  settings_terms_of_service: "Conditions d'utilisation",
  settings_terms_of_use: "Conditions d'usage",
  settings_delete_account: 'Supprimer le compte',
  settings_app_version: "Version de l'application 1.0.0",
  color_mode_title: 'Mode couleur',
  color_mode_section_label: 'Sélectionner le mode couleur',
  color_mode_system: 'Système par défaut',
  color_mode_light: 'Clair',
  color_mode_dark: 'Sombre',
  language_title: "Langues de l'application",
  language_section_label: 'Sélectionner la langue',
  language_english: 'Anglais',
  language_french: 'Français',
  offline_notice_title: 'Vous êtes hors ligne',
  offline_notice_description: 'Reconnectez-vous pour actualiser les trajets, tarifs et données en direct.',
  clear_all: 'Tout effacer',
  filter_title: 'Filtrer',
  filter_close_label: 'Fermer les filtres',
  filter_apply_results: 'Appliquer les filtres',
  generic_list_error_title: 'Impossible de charger les résultats',
  generic_list_error_description: 'Actualisez ou réessayez.',
  generic_list_retry: 'Réessayer',
  generic_list_empty_title: 'Aucun résultat trouvé',
  generic_list_empty_description: 'Essayez une autre recherche ou modifiez vos filtres.',
  generic_list_search_placeholder: 'Recherche',
  see_all_map_loading_title: 'Recherche de {{title}}',
  see_all_map_loading_description: 'Cela peut prendre quelques instants. Veuillez rester sur cet écran.',
  see_all_map_sheet_title: 'Restaurant',
  see_all_map_cta: 'Voir le restaurant',
  see_all_back_label: 'Retour',
  see_all_open_filters_label: 'Ouvrir les filtres',
  see_all_map_view_label: 'Vue carte',
  // Search components translations
  no_results_found: 'Aucun résultat trouvé',
  recent_searches: 'Recherches récentes',
  searching_near: 'Recherche près de',
  multi_vendor_address_label: 'Sélectionner une adresse',
  // Search filter translations
  search_filter_title: 'Filtres de recherche',
  search_filter_sort_by: 'Trier par',
  search_filter_sort_best_match: 'Meilleure correspondance',
  search_filter_sort_top_rated: 'Mieux notés',
  search_filter_sort_nearest: 'Plus proches',
  search_filter_ratings: 'Note minimum',
  search_filter_availability: 'Disponibilité',
  search_filter_availability_standard: 'Standard',
  search_filter_availability_emergency: 'Urgence',
  search_filter_stars: 'étoiles',
  filter_button_label: 'Options de filtre',
  search_input_placeholder: "Rechercher n'importe quoi",
};

export default fr;
