const en = {
  label: 'Deliveries',
  description: 'Order from stores or vendors.',
  header_title: 'Deliveries',
  header_subtitle: 'Choose a delivery type',
  single_vendor_title: 'Single Vendor',
  single_vendor_desc: 'Order from your preferred store.',
  multi_vendor_title: 'Multi Vendor',
  multi_vendor_desc: 'Browse and order from multiple stores.',
  chain_title: 'Chain',
  chain_desc: 'Order from your favorite chains.',
  explore_button: 'Explore',
  details_title: 'Delivery Details',
  single_vendor_home_subtitle: 'Your preferred store',
  single_vendor_home_body: 'Explore vendors and services here.',
  multi_vendor_home_subtitle: 'Browse multiple stores',
  multi_vendor_home_body: 'Discover and order from multiple vendors.',
  multi_vendor_tab_home: 'Home',
  multi_vendor_tab_search: 'Search',
  multi_vendor_tab_orders: 'Orders',
  multi_vendor_tab_profile: 'Profile',
  multi_vendor_address_label: 'Zone 6, Street 102 Doha, Qatar',
  multi_vendor_shop_types_title: 'Shop Types',
  multi_vendor_see_all: 'See all',
  multi_vendor_cart_label: 'Cart',
  multi_vendor_shop_type_gift: 'Gift Delivery',
  multi_vendor_shop_type_milk: 'Milk Delivery',
  multi_vendor_shop_type_flower: 'Flower Delivery',
  multi_vendor_shop_type_liquor: 'Liquor Delivery',
  chain_home_subtitle: 'Favorite chains',
  chain_home_body: 'Order from your favorite chain stores.',
  type_single_vendor_title: 'Single Vendor Store',
  type_single_vendor_desc: 'Hand-picked premium vendors only',
  type_marketplace_title: 'Marketplace',
  type_marketplace_desc: 'Vast Local Community providers',
  type_chain_title: 'Chain Stores',
  type_chain_desc: 'Shop your favorite chains',
  // Profile screen
  profile_personal_account: 'Personal account',
  profile_wallet_balance: 'Wallet Balance',
  profile_view_wallet: 'View wallet',
  profile_menu_profile: 'Profile',
  profile_menu_notifications: 'Notifications',
  profile_menu_favorites: 'Favorites',
  profile_menu_coupons: 'Coupons',
  profile_menu_settings: 'Settings',
  profile_menu_support: 'Support',
  profile_menu_color_mode: 'App color mode',
  profile_menu_language: 'English',
  profile_menu_logout: 'Log out',
  // My Profile screen
  my_profile_title: 'My profile',
  my_profile_edit: 'Edit',
  my_profile_full_name: 'Full name',
  my_profile_date_of_birth: 'Date of birth',
  my_profile_mobile_number: 'Mobile number',
  my_profile_email: 'Email',
  my_profile_my_addresses: 'My addresses',
  my_profile_add_address: 'Add address',
  my_profile_address_home: 'Home',
  my_profile_address_apartment: 'Apartment',
  my_profile_address_work: 'Work',
  my_profile_address_other: 'Other',
  // Profile photo modal
  photo_modal_title: 'Profile Photo',
  photo_modal_description: 'Choose how you want to update your profile photo',
  photo_take_photo: 'Take Photo',
  photo_choose_gallery: 'Choose from Gallery',
  photo_cancel: 'Cancel',
  photo_permission_title: 'Permission required',
  photo_permission_camera: 'Camera access is needed to take a photo.',
  photo_permission_gallery: 'Gallery access is needed to pick a photo.',
  photo_upload_error_title: 'Upload Failed',
  photo_upload_failed: 'Could not update profile photo.',
  // Edit Profile screen
  edit_profile_title: 'Edit profile',
  edit_profile_name: 'Name',
  edit_profile_date_of_birth: 'Date of birth',
  edit_profile_day: 'Day',
  edit_profile_month: 'Month',
  edit_profile_year: 'Year',
  edit_profile_gender: 'Gender',
  edit_profile_gender_placeholder: 'Select option',
  edit_profile_save: 'Save',
  edit_profile_success: 'Success',
  edit_profile_success_message: 'Profile updated successfully.',
  edit_profile_error: 'Error',
  edit_profile_name_required: 'Name is required.',
  edit_profile_failed: 'Could not update profile.',
  // Address screens
  address_list_title: 'My addresses',
  address_add_title: 'Add address',
  address_edit_title: 'Edit address',
  address_search_placeholder: 'Search for an address',
  address_choose_on_map: 'Choose on map',
  address_recent_searches: 'Recent searches',
  address_no_results: 'No results found',
  address_confirm_location: 'Confirm location',
  address_locating: 'Locating…',
  address_selected_location: 'Selected location',
  address_location_name_placeholder: 'Location name (e.g. My home)',
  address_details_label: 'Address Details',
  address_location_type_label: 'Location Type',
  address_type_home: 'Home',
  address_type_apartment: 'Apartment',
  address_type_office: 'Office',
  address_type_other: 'Other',
  address_save: 'Save address',
  address_update: 'Update address',
  address_delete: 'Delete',
  address_delete_confirm_title: 'Delete address',
  address_delete_confirm_message: 'Are you sure you want to delete this address?',
  address_delete_cancel: 'Cancel',
  address_delete_confirm: 'Delete',
  address_save_error: 'Could not save address.',
  address_delete_error: 'Could not delete address.',
  address_save_success: 'Address saved successfully.',
  address_update_success: 'Address updated successfully.',
  address_delete_success: 'Address deleted successfully.',
  searching_near: 'Searching near',
  search_input_placeholder: 'Search restaurants, stores, items',
  no_results_found: 'No results found',
  products: 'Products',
  stores: 'Stores',
  see_all: 'See All',
  recent_searches: 'Recent searches',
  clear_all: 'Clear all',
};

export default en;
