const en = {
  label: 'Deliveries',
  description: 'Order from stores or vendors.',
  header_title: 'Deliveries',
  header_subtitle: 'Choose a delivery type',
  single_vendor_title: 'Single Vendor',
  single_vendor_desc: 'Order from your preferred store.',
  multi_vendor_title: 'Multi Vendor',
  multi_vendor_desc: 'Browse and order from multiple stores.',
  chain_title: 'Chain',
  chain_desc: 'Order from your favorite chains.',
  explore_button: 'Explore',
  details_title: 'Delivery Details',
  single_vendor_home_subtitle: 'Your preferred store',
  single_vendor_home_body: 'Explore vendors and services here.',
  multi_vendor_home_subtitle: 'Browse multiple stores',
  multi_vendor_home_body: 'Discover and order from multiple vendors.',
  multi_vendor_tab_home: 'Home',
  multi_vendor_tab_search: 'Search',
  multi_vendor_tab_orders: 'Orders',
  multi_vendor_tab_profile: 'Profile',
  multi_vendor_address_label: 'Zone 6, Street 102 Doha, Qatar',
  multi_vendor_shop_types_title: 'Shop Types',
  multi_vendor_top_brands_title: 'Top Brands',
  multi_vendor_nearby_store_title: 'Nearby Store',
  multi_vendor_deals_title: 'Deals',
  multi_vendor_order_again_title: 'Order Again 😋',
  multi_vendor_see_all: 'See all',
  multi_vendor_order_again_add_item: 'Add item',
  multi_vendor_order_again_price_unavailable: 'Price unavailable',
  multi_vendor_nearby_store_name_hardees: 'Hardee’s - Z Block',
  multi_vendor_nearby_store_name_subway: 'Subway - Z Block',
  multi_vendor_nearby_store_category_fast_food: 'Fast Food',
  multi_vendor_nearby_store_category_pure_veg: 'Pure veg',
  multi_vendor_nearby_store_review_count: '(5000+)',
  multi_vendor_nearby_store_delivery_fee: '$2',
  multi_vendor_nearby_store_delivery_time: '30 mins',
  multi_vendor_nearby_store_distance: '1.7 km',
  multi_vendor_sponsored_label: 'Sponsored',
  multi_vendor_cart_label: 'Cart',
  multi_vendor_shop_type_gift: 'Gift Delivery',
  multi_vendor_shop_type_milk: 'Milk Delivery',
  multi_vendor_shop_type_flower: 'Flower Delivery',
  multi_vendor_shop_type_liquor: 'Liquor Delivery',
  multi_vendor_shop_type_products_empty: 'No products found for this shop type.',
  multi_vendor_shop_type_products_error: 'Unable to load products right now.',
  store_details_search_placeholder: 'Search',
  store_details_hero_title: 'Make It A\nMeal.',
  store_details_store_name: 'Subway @ Old Town, New Mexico',
  store_details_store_phone: '555-0123',
  store_details_store_email: 'support@subway.com',
  store_details_store_hours: '9 AM to 6 PM',
  store_details_call_label: 'Call us at',
  store_details_email_label: 'or email at',
  store_details_tab_offers: 'Offers',
  store_details_tab_pizza: 'Pizza',
  store_details_tab_burgers: 'Burgers',
  store_details_tab_pasta: 'Pasta',
  store_details_tab_sushi: 'Sushi',
  store_details_subcategory_italian_classic: 'Italian Classic',
  store_details_subcategory_american_style: 'American Style',
  store_details_subcategory_pepperoni: 'Pepperoni',
  store_details_subcategory_bbq_chicken: 'BBQ Chicken',
  store_details_subcategory_thin_crust: 'Thin Crust',
  store_details_all_offered_items: 'All Offered Items',
  store_details_no_items: 'No items match this filter yet.',
  store_details_load_error: 'Unable to load store details right now.',
  store_details_hours_unavailable: 'Hours unavailable',
  store_details_store_missing: 'Store details are not available.',
  store_details_action_info: 'Store info',
  store_details_action_favorite: 'Add store to favourites',
  store_details_action_share: 'Share store',
  store_details_action_back: 'Go back',
  store_details_about_title: 'About Us',
  store_details_about_fallback: 'Store description is not available right now.',
  store_details_close: 'Close',
  store_details_add_product: 'Add {{item}}',
  store_details_badge_deal: 'Deal',
  store_details_badge_ten_percent_off: '10% off',
  store_details_item_chicken_fajita: 'Chicken Fajita',
  store_details_item_chicken_teriyaki: 'Chicken Teriyaki',
  store_details_item_burger: 'Burger',
  store_details_item_sushi: 'Sushi',
  store_details_item_alfredo_pasta: 'Alfredo Pasta',
  store_details_item_veggie_delight: 'Veggie Delight',
  chain_home_subtitle: 'Favorite chains',
  chain_home_body: 'Order from your favorite chain stores.',
  type_single_vendor_title: 'Single Vendor Store',
  type_single_vendor_desc: 'Hand-picked premium vendors only',
  type_marketplace_title: 'Marketplace',
  type_marketplace_desc: 'Vast Local Community providers',
  type_chain_title: 'Chain Stores',
  type_chain_desc: 'Shop your favorite chains',
  // Profile screen
  profile_personal_account: 'Personal account',
  profile_wallet_balance: 'Wallet Balance',
  profile_view_wallet: 'View wallet',
  profile_menu_profile: 'Profile',
  profile_menu_notifications: 'Notifications',
  profile_menu_favorites: 'Favorites',
  profile_menu_coupons: 'Coupons',
  profile_menu_settings: 'Settings',
  profile_menu_support: 'Support',
  profile_menu_color_mode: 'App color mode',
  profile_menu_language: 'English',
  profile_menu_logout: 'Log out',
  // My Profile screen
  my_profile_title: 'My profile',
  my_profile_edit: 'Edit',
  my_profile_full_name: 'Full name',
  my_profile_date_of_birth: 'Date of birth',
  my_profile_mobile_number: 'Mobile number',
  my_profile_email: 'Email',
  my_profile_my_addresses: 'My addresses',
  my_profile_add_address: 'Add address',
  my_profile_address_home: 'Home',
  my_profile_address_apartment: 'Apartment',
  my_profile_address_work: 'Work',
  my_profile_address_other: 'Other',
  // Profile photo modal
  photo_modal_title: 'Profile Photo',
  photo_modal_description: 'Choose how you want to update your profile photo',
  photo_take_photo: 'Take Photo',
  photo_choose_gallery: 'Choose from Gallery',
  photo_cancel: 'Cancel',
  photo_permission_title: 'Permission required',
  photo_permission_camera: 'Camera access is needed to take a photo.',
  photo_permission_gallery: 'Gallery access is needed to pick a photo.',
  photo_upload_error_title: 'Upload Failed',
  photo_upload_failed: 'Could not update profile photo.',
  // Edit Profile screen
  edit_profile_title: 'Edit profile',
  edit_profile_name: 'Name',
  edit_profile_date_of_birth: 'Date of birth',
  edit_profile_day: 'Day',
  edit_profile_month: 'Month',
  edit_profile_year: 'Year',
  edit_profile_gender: 'Gender',
  edit_profile_gender_placeholder: 'Select option',
  edit_profile_save: 'Save',
  edit_profile_success: 'Success',
  edit_profile_success_message: 'Profile updated successfully.',
  edit_profile_error: 'Error',
  edit_profile_name_required: 'Name is required.',
  edit_profile_failed: 'Could not update profile.',
  // Address screens
  address_list_title: 'My addresses',
  address_add_title: 'Add address',
  address_edit_title: 'Edit address',
  address_search_placeholder: 'Search for an address',
  address_choose_on_map: 'Choose on map',
  address_recent_searches: 'Recent searches',
  address_no_results: 'No results found',
  address_confirm_location: 'Confirm location',
  address_locating: 'Locating…',
  address_selected_location: 'Selected location',
  address_location_name_placeholder: 'Location name (e.g. My home)',
  address_details_label: 'Address Details',
  address_location_type_label: 'Location Type',
  address_type_home: 'Home',
  address_type_apartment: 'Apartment',
  address_type_office: 'Office',
  address_type_other: 'Other',
  address_save: 'Save address',
  address_update: 'Update address',
  address_delete: 'Delete',
  address_delete_confirm_title: 'Delete address',
  address_delete_confirm_message: 'Are you sure you want to delete this address?',
  address_delete_cancel: 'Cancel',
  address_delete_confirm: 'Delete',
  address_save_error: 'Could not save address.',
  address_delete_error: 'Could not delete address.',
  address_save_success: 'Address saved successfully.',
  address_update_success: 'Address updated successfully.',
  address_delete_success: 'Address deleted successfully.',
  // Favourites screen
  favourites_title: 'Your Favourites',
  favourites_empty_title: 'No favourites yet',
  favourites_empty_subtitle: 'Stores you favourite will appear here.',
  favourites_error: 'Failed to load favourites. Pull down to retry.',
  favourites_free_delivery: 'Free delivery',
  favourites_remove: 'Remove from favourites',
  favourites_add: 'Add to favourites',
  favourites_toggle_added: 'Added to favourites',
  favourites_toggle_removed: 'Removed from favourites',
  favourites_toggle_error: 'Failed to update favourites',
  // Rate order screen
  rate_order_title: 'Rate Your Order',
  rate_order_heading: 'How was your meal?',
  rate_order_subheading: 'Your feedback helps us improve our delivery.',
  rate_order_comment_placeholder: 'Write your experience here...',
  rate_order_submit: 'Submit',
  rider_chat_title: 'Chat with Rider',
  rider_chat_subtitle: 'Live delivery updates',
  rider_chat_status_online: 'Online now',
  rider_chat_eta_label: '{{minutes}} min away',
  rider_chat_order_label: 'Order {{orderCode}}',
  rider_chat_help_text: 'Share pickup notes or ask for an arrival call.',
  rider_chat_message_rider_intro: 'Hi! I am on the way with your order.',
  rider_chat_message_user_reply: 'Perfect. Please call me when you arrive at the gate.',
  rider_chat_message_rider_eta: 'Sure, I will call you. See you in about {{minutes}} minutes.',
  rider_chat_quick_reply_gate: 'Call at gate',
  rider_chat_quick_reply_thanks: 'Thanks!',
  rider_chat_quick_reply_here: 'I’m here',
  rider_chat_quick_reply_hello: 'Hello',
  rider_chat_quick_reply_call_arrive: 'Call me when you arrive',
  rider_chat_quick_reply_where: 'Where are you?',
  rider_chat_quick_reply_eta: 'How long will you take?',
  rider_chat_input_placeholder: 'Enter your concern...',
  rider_chat_auto_message: 'How can we help you?\n[Automessage]',
  rider_chat_auto_time: '8:29 pm',
  rider_chat_send: 'Send',
  rider_chat_send_error: 'Could not send message.',
  rider_chat_missing_session_error: 'Please log in before sending a message.',
  rider_chat_missing_receiver_error: 'Receiver is missing for this chat.',
  rider_chat_attachment_permission_title: 'Permission needed',
  rider_chat_attachment_permission_message: 'Please allow photo library access to add an attachment.',
  rider_chat_attachment_selected_title: 'Attachment selected',
  rider_chat_attachment_selected_message: '{{fileName}} is ready to attach.',
  rider_chat_add_attachment: 'Add attachment',
  rider_chat_send_message: 'Send message',
  rider_chat_call_action: 'Call rider',
  support_title: 'Support',
  support_guest_name: 'there',
  support_greeting: 'Hi {{name}}!',
  support_headline: 'What do you need help with today?',
  support_browse_topics: 'Browse help topics',
  support_topic_faq: 'Frequently asked questions',
  support_topic_conversations: 'My conversations',
  support_issue_prompt: 'Didn’t find what you need?',
  support_issue_select_title: 'Please select',
  support_issue_placeholder: 'Select an issue type',
  support_issue_order: 'I already have a business account and need support',
  support_issue_payment: 'I’m interested in joining Food delivery as a business',
  support_issue_delivery: 'I booked an order with a business on Food delivery',
  support_issue_account: 'I need help with something else',
  support_call_action: 'Call support',
  support_back_action: 'Go back',
  support_header_action: 'Header action',
  support_close_action: 'Close support form',
  support_search_action: 'Search conversations',
  support_form_how_help_label: 'How can we help?',
  support_form_email_label: 'Email',
  support_form_email_helper: 'If you have a Food delivery account, enter the email address you log in with',
  support_form_reason_label: 'Reason for contact',
  support_form_reason_placeholder: 'Please select',
  support_form_reason_login: 'Account access issue',
  support_form_reason_billing: 'Billing or business onboarding',
  support_form_reason_other: 'Something else',
  support_form_description_label: 'Describe what you need help with',
  support_form_description_placeholder: 'Enter a description...',
  support_form_attach_title: 'Attach screenshots',
  support_form_attach_description: 'Drop your files here',
  support_form_attach_cta: 'Choose a file',
  support_form_send_email: 'Send email',
  support_chat_agent_name: 'Jhon Smith',
  support_chat_auto_message: 'How can we help you?\n[Automessage]',
  support_chat_auto_time: '8:29 pm',
  support_chat_quick_reply_here: 'I’m here',
  support_chat_quick_reply_hello: 'Hello',
  support_chat_quick_reply_call_arrive: 'Call me when you arrive',
  support_chat_quick_reply_where: 'Where are you?',
  support_chat_quick_reply_eta: 'How long will you take?',
  support_chat_input_placeholder: 'Enter your concern...',
  support_chat_add_attachment: 'Add attachment',
  support_chat_send_message: 'Send message',
  support_chat_send_error_title: 'Message failed',
  support_chat_send_error_message: 'Could not send your support message.',
  support_chat_missing_session_error: 'Please log in before sending a message.',
  support_chat_missing_receiver_error: 'Support chat is not ready yet. Please open an existing conversation first.',
  support_chat_loading: 'Loading conversation...',
  support_chat_empty: 'No support conversation found yet.',
  support_chat_empty_message: 'Start a conversation with support.',
  support_chat_attachment_permission_title: 'Permission needed',
  support_chat_attachment_permission_message: 'Please allow photo library access to add an attachment.',
  support_chat_attachment_selected_title: 'Attachment selected',
  support_chat_attachment_selected_message: '{{fileName}} is ready to attach.',
  support_admin_picker_title: 'Choose support person',
  support_admin_picker_subtitle: 'Select an available admin to start your conversation.',
  support_admin_picker_loading: 'Loading support team...',
  support_admin_picker_empty: 'No support admins available right now.',
  support_admin_picker_row_subtitle: 'Tap to start conversation',
  support_conversations_title: 'My conversations',
  support_conversations_recent: 'Recent',
  support_conversations_past: 'Past',
  support_conversations_name_barbarella_inova: 'Barbarella Inova',
  support_conversations_name_barbarella_nova: 'Barbarella Nova',
  support_conversations_preview_let_me_check: 'Let me check.',
  support_conversations_preview_take_a_look: 'I’ll take a look.',
  support_conversations_time_5m: '5 min ago',
  support_conversations_time_1h: '1 hr ago',
  support_conversations_time_oct_2: '2 Oct',
  support_conversations_delete_action: 'Delete conversation',
  support_conversations_delete_title: 'Delete {{name}}’s chat?',
  support_conversations_delete_description: 'Are you sure you want to permanently delete this chat?',
  support_conversations_delete_cancel: 'Cancel',
  support_conversations_delete_confirm: 'Yes, Delete',
  support_conversations_loading: 'Loading conversations...',
  support_conversations_empty: 'No conversations yet.',
  support_faq_title: 'General order questions',
  support_faq_place_order: 'How to place an order',
  support_faq_schedule_delivery: 'How to schedule your deliveries in advance',
  support_faq_change_delivery: 'Changing your deliveries',
  support_faq_order_history: 'How to view your order history',
  support_faq_ordering_for_others: 'Ordering for others and sending confirmations to different addresses',
  support_faq_still_need_help: 'Still need some help?',
  support_faq_feedback_prompt: 'Was this helpful?',
  support_faq_feedback_yes: 'Yes',
  support_faq_feedback_no: 'No',
  support_faq_place_order_body_1: 'Placing an order is quick and simple. Open the deliveries app and browse nearby restaurants, stores, or categories that match what you need.',
  support_faq_place_order_body_2: 'Tap a store to explore its menu, then add the items you want to your cart. You can review quantities, add notes, and remove anything before checkout.',
  support_faq_place_order_body_3: 'When you are ready, continue to checkout to confirm your delivery address, apply any promo codes, and choose your preferred payment method.',
  support_faq_place_order_body_4: 'After you place the order, you can track its progress in real time and stay updated until it arrives at your door.',
  support_faq_schedule_delivery_body_1: 'If a store supports scheduled orders, you can choose a delivery time before you complete checkout.',
  support_faq_schedule_delivery_body_2: 'Add your items to the cart and proceed to checkout. Look for the delivery timing section before confirming your order.',
  support_faq_schedule_delivery_body_3: 'Select a date and time slot that works for you, then review the order details to make sure everything looks right.',
  support_faq_schedule_delivery_body_4: 'Once confirmed, we will keep your scheduled delivery in your orders tab so you can review it again later.',
  support_faq_change_delivery_body_1: 'You may be able to update parts of your order before the store starts preparing it.',
  support_faq_change_delivery_body_2: 'Open your active order and check whether editing is still available. Some stores allow small updates while others may lock changes once preparation begins.',
  support_faq_change_delivery_body_3: 'If editing is unavailable, the fastest option is usually to contact support from the help section or start a chat with a person.',
  support_faq_change_delivery_body_4: 'We recommend checking your cart carefully before placing the order so you can avoid last-minute changes.',
  support_faq_order_history_body_1: 'Your previous and active deliveries are available from the orders section in the app.',
  support_faq_order_history_body_2: 'Open the order you want to review to see its items, payment details, delivery address, and current or past status.',
  support_faq_order_history_body_3: 'This is also the best place to reorder items quickly when you want the same delivery again.',
  support_faq_ordering_for_others_body_1: 'You can place an order for someone else by selecting or entering the correct delivery address before checkout.',
  support_faq_ordering_for_others_body_2: 'Make sure the recipient name, phone number, and any delivery instructions are accurate so the courier can reach the right person.',
  support_faq_ordering_for_others_body_3: 'If you need to send updates to a different contact, review the available contact details during checkout and before confirming the order.',
  support_faq_ordering_for_others_body_4: 'For the smoothest experience, let the recipient know a delivery is on the way and share any timing details with them.',
  support_faq_still_need_help_body_1: 'If your question is not covered here, open the chat option at the bottom of the screen and reach out to our support team.',
  support_faq_still_need_help_body_2: 'Include key details such as the store name, order number, and a short explanation of the issue so we can help faster.',
  support_faq_still_need_help_body_3: 'Our team will guide you through the next steps and help resolve delivery, payment, or account-related concerns.',
  support_chat_cta: 'Chat with a person',
  searching_near: 'Searching near',
  search_input_placeholder: 'Search restaurants, stores, items',
  no_results_found: 'No results found',
  products: 'Products',
  stores: 'Stores',
  see_all: 'See All',
  recent_searches: 'Recent searches',
  clear_all: 'Clear all',
  filter_title: 'Filter',
  filter_close_label: 'Close filters',
  filter_apply_results: 'Apply filters',
  filter_category_title: 'Category',
  filter_price_title: 'Price',
  filter_address_title: 'Nearby address',
  filter_stock_title: 'Stock',
  filter_sort_title: 'Sort by',
  generic_list_error_title: 'Unable to load results',
  generic_list_error_description: 'Pull to refresh or try again.',
  generic_list_retry: 'Retry',
  generic_list_empty_title: 'No results found',
  generic_list_empty_description: 'Try a different search or adjust your filters.',
  generic_list_search_placeholder: 'Search',
  see_all_map_loading_title: 'Finding {{title}}',
  see_all_map_loading_description: 'This may take a few moments. Please stay on this screen.',
  see_all_map_sheet_title: 'Restaurant',
  see_all_map_cta: 'View Restaurant',
  // Change password flow
  change_password_title: 'Change Password',
  change_password_new_title: 'New Password',
  change_password_email_heading: 'Change password?',
  change_password_email_description: 'Enter your email address and we\'ll send you a verification code.',
  change_password_email_placeholder: 'your@email.com',
  change_password_continue: 'Continue',
  change_password_verify_heading: 'Verify Your Email',
  change_password_verify_description: 'Enter the 4-digit code sent to {{email}}',
  change_password_verify_button: 'Verify OTP',
  change_password_new_heading: 'Create your new password',
  change_password_new_description: 'Your new password must be different from your previous password.',
  change_password_new_placeholder: 'New password',
  change_password_confirm_placeholder: 'Confirm new password',
  change_password_set_new: 'Set new password',
  change_password_mismatch: 'Passwords do not match.',
  change_password_error_title: 'Error',
  change_password_send_otp_error: 'Failed to send verification code.',
  change_password_verify_otp_error: 'Invalid or expired code.',
  change_password_update_error: 'Failed to update password.',
  change_password_success_title: 'Success',
  change_password_success_message: 'Your password has been updated.',
  change_password_otp_resent_title: 'Code sent',
  change_password_otp_resent_message: 'A new verification code has been sent.',
  // Delete account flow
  delete_account_step_label: 'Delete my account',
  delete_account_sorry_heading: "We'll be sorry to see you go",
  delete_account_sorry_subtext: 'Can we change your mind? Drop a line at',
  delete_account_contact_email: 'hello@enategadelivery.com',
  delete_account_reason_heading: 'Why do you wish to leave Food delivery?',
  delete_account_reason_subtext: 'Please let us know the reason for deleting your account:',
  delete_account_reason_mistake: 'I created this account by mistake',
  delete_account_reason_no_longer: 'I do not want to use Food delivery anymore',
  delete_account_reason_no_venues: "I can't find the venues or services I want",
  delete_account_reason_other: 'Other',
  delete_account_confirm_heading: 'Delete your Food delivery account',
  delete_account_confirm_description: 'This action will delete your account and you won\'t be able to retrieve it. Please confirm you understand by ticking the below statements:',
  delete_account_confirm_item_orders: 'I know I won\'t be able to access my orders.',
  delete_account_confirm_item_marketplace: 'I know I will no longer be able to book orders via Food delivery marketplace.',
  delete_account_final_heading: 'Confirm you are happy to proceed',
  delete_account_final_description: 'Please note this is permanent and can\'t be undone. To confirm deleting your account, please review your email below:',
  delete_account_email_label: 'Email',
  delete_account_email_placeholder: 'your@email.com',
  delete_account_cta_continue: 'Continue',
  delete_account_cta_delete: 'Delete account',
  delete_account_close: 'Close',
  delete_account_alert_title: 'Delete account',
  delete_account_alert_message: 'Are you sure you want to permanently delete your account? This action cannot be undone.',
  delete_account_alert_cancel: 'Cancel',
  delete_account_alert_confirm: 'Delete',
  delete_account_error_title: 'Error',
  delete_account_error: 'Failed to delete account. Please try again.',
  // Color mode screen
  color_mode_title: 'App color mode',
  color_mode_section_label: 'Select app color mode',
  color_mode_system: 'Default System',
  color_mode_light: 'Light',
  color_mode_dark: 'Dark',
  // Language screen
  language_title: 'App languages',
  language_section_label: 'Select language',
  language_english: 'English',
  language_french: 'French',
  popular: 'Popular',
  ingredients: 'Ingredients',
  usage: 'Usage',
  nutrition_facts: 'Nutrition facts',
  amount_per: 'Amount per',
  energy: 'Energy',
  fat: 'Fat',
  carbohydrates: 'Carbohydrates',
  protein: 'Protein',
  sugar: 'Sugar',
  choose_size: 'Choose Size',
  choose_variation: 'Choose Variation',
  select_one: 'Select one',
  small: 'Small',
  medium: 'Medium',
  large: 'Large',
  choose_your_flavour: 'Choose your Flavour',
  choose_your_addons: 'Choose your Addons',
  add_to_cart: 'Add to Cart',
  free: 'Free',
  product_info_error_title: "Couldn't load product",
  orders_tab_active: 'Active orders',
  orders_tab_history: 'Order history',
  orders_tab_scheduled: 'Schedule orders',
  orders_empty_active_title: 'No active orders yet',
  orders_empty_active_subtitle: 'Your active orders will appear here once you place one.',
  orders_empty_history_title: 'No orders yet',
  orders_empty_history_subtitle: 'You haven’t made any order. It will show here when you made one.',
  orders_empty_history_cta: 'Start shopping',
  orders_empty_scheduled_title: 'No schedule deliveries yet',
  orders_empty_scheduled_subtitle: 'You haven’t schedule any order.',
  orders_history_ongoing_heading: 'Ongoing order',
  orders_history_past_heading: 'Past orders',
  orders_list_load_more: 'Load more',
  orders_list_no_more_items: 'No more items',
  orders_list_error: 'Unable to load scheduled deliveries right now.',
  orders_list_retry: 'Try again',
  orders_status_upcoming: 'Upcoming',
  orders_status_ongoing: 'Ongoing',
  orders_status_delivered: 'Order Delivered',
  orders_status_cancelled: 'Order Cancelled',
  order_details_title: 'Order details',
  order_details_error_title: 'Unable to load this order right now.',
  order_details_status: 'Order status',
  order_details_scheduled_for: 'Scheduled for',
  order_details_items: 'Order items',
  order_details_summary: 'Order summary',
  order_details_payment_details: 'Payment details',
  order_details_order_number: 'Order number',
  order_details_delivery_address: 'Delivery address',
  order_details_item_subtotal: 'Item subtotal',
  order_details_discount: 'Discount',
  order_details_tax: 'Tax',
  order_details_packing_charges: 'Packing charges',
  order_details_delivery_fee: 'Delivery',
  order_details_courier_tip: 'Courier tip',
  order_details_total_amount: 'Total amount',
  order_details_rate_order: 'Rate the order',
  order_details_increase_tip: 'Increase the tip',
  order_details_track_progress: 'Track progress',
  order_details_order_again: 'Order again',
  order_details_tip_done: 'Done',
  order_details_tip_placeholder: '0.00',
  order_details_empty_items: 'No items',
  order_details_quantity_one: 'Qty {{count}}',
  order_details_quantity_other: 'Qty {{count}}'
};

export default en;
