const en = {
  label: 'Deliveries',
  description: 'Order from stores or vendors.',
  header_title: 'Deliveries',
  header_subtitle: 'Choose a delivery type',
  single_vendor_title: 'Single Vendor',
  single_vendor_desc: 'Order from your preferred store.',
  multi_vendor_title: 'Multi Vendor',
  multi_vendor_desc: 'Browse and order from multiple stores.',
  chain_title: 'Chain',
  chain_desc: 'Order from your favorite chains.',
  explore_button: 'Explore',
  details_title: 'Delivery Details',
  single_vendor_home_subtitle: 'Your preferred store',
  single_vendor_home_body: 'Explore vendors and services here.',
  multi_vendor_home_subtitle: 'Browse multiple stores',
  multi_vendor_home_body: 'Discover and order from multiple vendors.',
  multi_vendor_tab_home: 'Home',
  multi_vendor_tab_search: 'Search',
  multi_vendor_tab_orders: 'Orders',
  multi_vendor_tab_profile: 'Profile',
  multi_vendor_address_label: 'Zone 6, Street 102 Doha, Qatar',
  multi_vendor_shop_types_title: 'Shop Types',
  multi_vendor_top_brands_title: 'Top Brands',
  multi_vendor_nearby_store_title: 'Nearby Store',
  multi_vendor_deals_title: 'Deals',
  multi_vendor_order_again_title: 'Order Again 😋',
  multi_vendor_see_all: 'See all',
  multi_vendor_order_again_add_item: 'Add item',
  multi_vendor_order_again_price_unavailable: 'Price unavailable',
  multi_vendor_nearby_store_name_hardees: 'Hardee’s - Z Block',
  multi_vendor_nearby_store_name_subway: 'Subway - Z Block',
  multi_vendor_nearby_store_category_fast_food: 'Fast Food',
  multi_vendor_nearby_store_category_pure_veg: 'Pure veg',
  multi_vendor_nearby_store_review_count: '(5000+)',
  multi_vendor_nearby_store_delivery_fee: '$2',
  multi_vendor_nearby_store_delivery_time: '30 mins',
  multi_vendor_nearby_store_distance: '1.7 km',
  multi_vendor_sponsored_label: 'Sponsored',
  multi_vendor_cart_label: 'Cart',
  multi_vendor_shop_type_gift: 'Gift Delivery',
  multi_vendor_shop_type_milk: 'Milk Delivery',
  multi_vendor_shop_type_flower: 'Flower Delivery',
  multi_vendor_shop_type_liquor: 'Liquor Delivery',
  multi_vendor_shop_type_products_empty: 'No products found for this shop type.',
  multi_vendor_shop_type_products_error: 'Unable to load products right now.',
  chain_home_subtitle: 'Favorite chains',
  chain_home_body: 'Order from your favorite chain stores.',
  type_single_vendor_title: 'Single Vendor Store',
  type_single_vendor_desc: 'Hand-picked premium vendors only',
  type_marketplace_title: 'Marketplace',
  type_marketplace_desc: 'Vast Local Community providers',
  type_chain_title: 'Chain Stores',
  type_chain_desc: 'Shop your favorite chains',
  // Profile screen
  profile_personal_account: 'Personal account',
  profile_wallet_balance: 'Wallet Balance',
  profile_view_wallet: 'View wallet',
  profile_menu_profile: 'Profile',
  profile_menu_notifications: 'Notifications',
  profile_menu_favorites: 'Favorites',
  profile_menu_coupons: 'Coupons',
  profile_menu_settings: 'Settings',
  profile_menu_support: 'Support',
  profile_menu_color_mode: 'App color mode',
  profile_menu_language: 'English',
  profile_menu_logout: 'Log out',
  // My Profile screen
  my_profile_title: 'My profile',
  my_profile_edit: 'Edit',
  my_profile_full_name: 'Full name',
  my_profile_date_of_birth: 'Date of birth',
  my_profile_mobile_number: 'Mobile number',
  my_profile_email: 'Email',
  my_profile_my_addresses: 'My addresses',
  my_profile_add_address: 'Add address',
  my_profile_address_home: 'Home',
  my_profile_address_apartment: 'Apartment',
  my_profile_address_work: 'Work',
  my_profile_address_other: 'Other',
  // Profile photo modal
  photo_modal_title: 'Profile Photo',
  photo_modal_description: 'Choose how you want to update your profile photo',
  photo_take_photo: 'Take Photo',
  photo_choose_gallery: 'Choose from Gallery',
  photo_cancel: 'Cancel',
  photo_permission_title: 'Permission required',
  photo_permission_camera: 'Camera access is needed to take a photo.',
  photo_permission_gallery: 'Gallery access is needed to pick a photo.',
  photo_upload_error_title: 'Upload Failed',
  photo_upload_failed: 'Could not update profile photo.',
  // Edit Profile screen
  edit_profile_title: 'Edit profile',
  edit_profile_name: 'Name',
  edit_profile_date_of_birth: 'Date of birth',
  edit_profile_day: 'Day',
  edit_profile_month: 'Month',
  edit_profile_year: 'Year',
  edit_profile_gender: 'Gender',
  edit_profile_gender_placeholder: 'Select option',
  edit_profile_save: 'Save',
  edit_profile_success: 'Success',
  edit_profile_success_message: 'Profile updated successfully.',
  edit_profile_error: 'Error',
  edit_profile_name_required: 'Name is required.',
  edit_profile_failed: 'Could not update profile.',
  // Address screens
  address_list_title: 'My addresses',
  address_add_title: 'Add address',
  address_edit_title: 'Edit address',
  address_search_placeholder: 'Search for an address',
  address_choose_on_map: 'Choose on map',
  address_recent_searches: 'Recent searches',
  address_no_results: 'No results found',
  address_confirm_location: 'Confirm location',
  address_locating: 'Locating…',
  address_selected_location: 'Selected location',
  address_location_name_placeholder: 'Location name (e.g. My home)',
  address_details_label: 'Address Details',
  address_location_type_label: 'Location Type',
  address_type_home: 'Home',
  address_type_apartment: 'Apartment',
  address_type_office: 'Office',
  address_type_other: 'Other',
  address_save: 'Save address',
  address_update: 'Update address',
  address_delete: 'Delete',
  address_delete_confirm_title: 'Delete address',
  address_delete_confirm_message: 'Are you sure you want to delete this address?',
  address_delete_cancel: 'Cancel',
  address_delete_confirm: 'Delete',
  address_save_error: 'Could not save address.',
  address_delete_error: 'Could not delete address.',
  address_save_success: 'Address saved successfully.',
  address_update_success: 'Address updated successfully.',
  address_delete_success: 'Address deleted successfully.',
  // Favourites screen
  favourites_title: 'Your Favourites',
  favourites_empty_title: 'No favourites yet',
  favourites_empty_subtitle: 'Stores you favourite will appear here.',
  favourites_error: 'Failed to load favourites. Pull down to retry.',
  favourites_free_delivery: 'Free delivery',
  favourites_remove: 'Remove from favourites',
  favourites_add: 'Add to favourites',
  favourites_toggle_added: 'Added to favourites',
  favourites_toggle_removed: 'Removed from favourites',
  favourites_toggle_error: 'Failed to update favourites',
  // Rate order screen
  rate_order_title: 'Rate Your Order',
  rate_order_heading: 'How was your meal?',
  rate_order_subheading: 'Your feedback helps us improve our delivery.',
  rate_order_comment_placeholder: 'Write your experience here...',
  rate_order_submit: 'Submit',
  rate_order_success_title: 'Thank you!',
  rate_order_success_message: 'Your review has been submitted.',
  rate_order_error_title: 'Submission failed',
  // Settings screen
  settings_title: 'Settings',
  settings_notifications: 'Notifications Setting',
  settings_change_password: 'Change password',
  settings_privacy_policy: 'Privacy policy',
  settings_terms_of_service: 'Terms of service',
  settings_terms_of_use: 'Terms of use',
  settings_delete_account: 'Delete account',
  settings_app_version: 'App version 1.0.0',
  // Notification settings screen
  notif_settings_title: 'Notification settings',
  notif_settings_food_delivery: 'Food delivery notifications',
  notif_settings_marketing: 'Marketing notifications',
  notif_settings_email: 'Email',
  notif_settings_sms: 'Text message',
  notif_settings_whatsapp: 'WhatsApp',
  notif_settings_success_title: 'Saved',
  notif_settings_success_message: 'Notification preference updated.',
  notif_settings_error_title: 'Error',
  // Privacy Policy screen
  privacy_screen_header: 'Privacy Policy',
  privacy_title: 'Privacy Policy',
  privacy_last_updated: 'Last updated 2 months ago',
  privacy_intro: 'This Privacy Policy explains how we handle your personal information when using the Food Delivery App. By signing up or accessing the app, you consent to the practices outlined in this Policy. If you do not agree, please do not use the Food Delivery App.',
  privacy_section_app_title: 'Privacy Policy for the App',
  privacy_section_app_body: 'The Food Delivery App is committed to protecting and managing your personal data and orders securely. You are permitted to use the app for both personal and commercial purposes, provided you comply with this Policy and all applicable laws. It is essential to keep your login credentials confidential, as you bear full responsibility for all actions taken under your account.\n\nAny misuse of the Food Delivery App, such as unauthorized access, service disruptions, or illegal conduct, is strictly forbidden. Attempts to bypass security protocols or overload our servers are also prohibited.',
  privacy_section_responsibilities_title: 'User Responsibilities',
  privacy_section_responsibilities_body: 'Users are responsible for ensuring the accuracy of their delivery addresses and payment information. It is important to keep these details updated to avoid any issues during the order process. Users should also refrain from sharing their account with others to protect their personal information.',
  privacy_section_data_title: 'Data Collection',
  privacy_section_data_body: 'The Food Delivery App collects essential data to enhance your experience, including your location, order history, and preferences. This information allows us to provide personalized recommendations and improve our services. We ensure that all data collected is stored securely and used solely for the intended purposes.',
  privacy_section_modifications_title: 'Order Modifications',
  privacy_section_modifications_body: 'You can modify or cancel your orders through the app before they are processed. Once an order is confirmed, changes may not be possible. Please review your order details carefully to ensure they meet your requirements prior to confirmation.',
  privacy_section_payment_title: 'Payment Security',
  privacy_section_payment_body: 'We prioritize the security of your payment information. All transactions made through the Food Delivery App are processed using industry-standard encryption technology. We do not store your credit card information on our servers to further enhance your security.',
  privacy_section_contact_title: 'Get in Touch',
  privacy_section_contact_body: 'If you have any questions about these Terms, feel free to contact us:',
  privacy_contact_email: 'Email: contact@fooddelivery.com',
  privacy_contact_address: 'Address: Doha, Qatar',
  // Terms of Service screen
  tos_screen_header: 'Terms of Service',
  tos_title: 'Terms of Service',
  tos_last_updated: 'last updated 2 months ago',
  tos_intro: 'These Terms of Service ("Terms") outline your access to and use of the Food Delivery App. By creating an account or using the app, you agree to adhere to these Terms. If you disagree, please refrain from using the Food Delivery App.',
  tos_section_usage_title: 'Service Usage',
  tos_section_usage_body: 'The Food Delivery App provides a reliable platform for ordering and managing your meal deliveries. Users can utilize the app for personal enjoyment or business needs, provided they adhere to these Terms and applicable laws. It\'s important to safeguard your account information, as you are liable for any actions taken under your account.\n\nAbusing the Food Delivery App, including attempts to hack, disrupt, replicate, or resell our services, is strictly prohibited. Any attempts to circumvent security protocols, overload our systems, or partake in illicit activities are not permitted.',
  tos_section_orders_title: 'Order Management',
  tos_section_orders_body: 'The app allows you to easily track your orders, modify details, or cancel them within the specified time frame. Users should ensure they review their selections to avoid errors or unwanted costs.\n\nAny random or unauthorized alterations to orders that disrupt the service are not tolerated, and repeated violations may result in account suspension.',
  tos_section_payment_title: 'Payment Security',
  tos_section_payment_body: 'Payments through the Food Delivery App are handled securely with encryption technology to protect your financial information. Ensure that you are using a secure network when processing transactions to avoid potential fraud.\n\nSharing your payment information with others or engaging in fraudulent activities is strictly forbidden and may lead to immediate account termination.',
  tos_section_delivery_title: 'Delivery Policies',
  tos_section_delivery_body: 'Users are encouraged to provide accurate delivery addresses to facilitate prompt and efficient service. The app may offer options for contactless delivery to enhance safety. Make sure to be available for your delivery to avoid inconvenience.\n\nFailing to provide correct information or obstructing delivery personnel is against our policies and could result in penalties.',
  tos_section_support_title: 'Customer Support',
  tos_section_support_body: 'The Food Delivery App provides a robust support system to address any issues or inquiries. Users can reach out via chat or email, and we strive to respond promptly to all requests.\n\nInappropriate behavior towards support staff or abusing the communication channels will not be tolerated and can lead to service restrictions.',
  tos_section_contact_title: 'Get in Touch',
  tos_section_contact_body: 'If you have any questions about these Terms, feel free to contact us:',
  tos_contact_email: 'Email: contact@fooddelivery.com',
  tos_contact_address: 'Address: Doha, Qatar',
  // Terms of Use screen
  tou_screen_header: 'Terms of Use',
  tou_title: 'Terms of Use',
  tou_last_updated: 'updated 2 months ago',
  tou_intro: 'These User Agreement Terms ("Terms") outline your rights and responsibilities when using the Food Delivery App. By signing up or accessing the app, you agree to follow these Terms. If you disagree, please refrain from using the Food Delivery App.',
  tou_section_guidelines_title: 'App Usage Guidelines',
  tou_section_guidelines_body: 'The Food Delivery App provides secure management and storage for your orders and customer data. You can use the app for personal or business purposes, as long as you adhere to these Terms and all applicable laws. Keep your login details confidential, as you are responsible for all activities conducted under your account.\n\nAny misuse of the Food Delivery App, including hacking attempts, service disruptions, copying, or reselling our services, is strictly prohibited. Activities aimed at bypassing security measures, overloading servers, or engaging in illegal actions are not allowed.',
  tou_section_etiquette_title: 'Delivery Etiquette',
  tou_section_etiquette_body: 'Users are expected to maintain respect and courtesy towards delivery personnel. Any form of harassment or inappropriate behavior towards staff will result in account suspension.',
  tou_section_payment_title: 'Payment Methods',
  tou_section_payment_body: 'The Food Delivery App supports multiple payment methods including credit cards, digital wallets, and cash on delivery. Ensure that your payment information is up to date to avoid any transaction issues.',
  tou_section_cancellation_title: 'Cancellation Policy',
  tou_section_cancellation_body: 'Orders can be canceled within a 10-minute window after placing them. Cancellations after this period may incur a fee depending on the restaurant\'s policy.',
  tou_section_feedback_title: 'Feedback and Ratings',
  tou_section_feedback_body: 'Users are encouraged to provide feedback on their delivery experience. Ratings help improve service and guide other customers in their decision-making. Inappropriate reviews may be removed.',
  tou_section_promotions_title: 'Promotions and Offers',
  tou_section_promotions_body: 'The Food Delivery App may offer promotions and discounts. These offers are subject to change and may have specific terms and conditions which users should read carefully before applying.',
  tou_section_contact_title: 'Get in Touch',
  tou_section_contact_body: 'If you have any questions about these Terms, feel free to contact us:',
  tou_contact_email: 'Email: contact@fooddelivery.com',
  tou_contact_address: 'Address: Doha, Qatar',
  searching_near: 'Searching near',
  search_input_placeholder: 'Search restaurants, stores, items',
  no_results_found: 'No results found',
  products: 'Products',
  stores: 'Stores',
  see_all: 'See All',
  recent_searches: 'Recent searches',
  clear_all: 'Clear all',
  filter_title: 'Filter',
  filter_close_label: 'Close filters',
  filter_apply_results: 'Apply filters',
  filter_category_title: 'Category',
  filter_price_title: 'Price',
  filter_address_title: 'Nearby address',
  filter_stock_title: 'Stock',
  filter_sort_title: 'Sort by',
  generic_list_error_title: 'Unable to load results',
  generic_list_error_description: 'Pull to refresh or try again.',
  generic_list_retry: 'Retry',
  generic_list_empty_title: 'No results found',
  generic_list_empty_description: 'Try a different search or adjust your filters.',
  generic_list_search_placeholder: 'Search',
  see_all_map_loading_title: 'Finding {{title}}',
  see_all_map_loading_description: 'This may take a few moments. Please stay on this screen.',
  see_all_map_sheet_title: 'Restaurant',
  see_all_map_cta: 'View Restaurant',
  // Change password flow
  change_password_title: 'Change Password',
  change_password_new_title: 'New Password',
  change_password_email_heading: 'Change password?',
  change_password_email_description: 'Enter your email address and we\'ll send you a verification code.',
  change_password_email_placeholder: 'your@email.com',
  change_password_continue: 'Continue',
  change_password_verify_heading: 'Verify Your Email',
  change_password_verify_description: 'Enter the 4-digit code sent to {{email}}',
  change_password_verify_button: 'Verify OTP',
  change_password_new_heading: 'Create your new password',
  change_password_new_description: 'Your new password must be different from your previous password.',
  change_password_new_placeholder: 'New password',
  change_password_confirm_placeholder: 'Confirm new password',
  change_password_set_new: 'Set new password',
  change_password_mismatch: 'Passwords do not match.',
  change_password_error_title: 'Error',
  change_password_send_otp_error: 'Failed to send verification code.',
  change_password_verify_otp_error: 'Invalid or expired code.',
  change_password_update_error: 'Failed to update password.',
  change_password_success_title: 'Success',
  change_password_success_message: 'Your password has been updated.',
  change_password_otp_resent_title: 'Code sent',
  change_password_otp_resent_message: 'A new verification code has been sent.',
  // Delete account flow
  delete_account_step_label: 'Delete my account',
  delete_account_sorry_heading: "We'll be sorry to see you go",
  delete_account_sorry_subtext: 'Can we change your mind? Drop a line at',
  delete_account_contact_email: 'hello@enategadelivery.com',
  delete_account_reason_heading: 'Why do you wish to leave Food delivery?',
  delete_account_reason_subtext: 'Please let us know the reason for deleting your account:',
  delete_account_reason_mistake: 'I created this account by mistake',
  delete_account_reason_no_longer: 'I do not want to use Food delivery anymore',
  delete_account_reason_no_venues: "I can't find the venues or services I want",
  delete_account_reason_other: 'Other',
  delete_account_confirm_heading: 'Delete your Food delivery account',
  delete_account_confirm_description: 'This action will delete your account and you won\'t be able to retrieve it. Please confirm you understand by ticking the below statements:',
  delete_account_confirm_item_orders: 'I know I won\'t be able to access my orders.',
  delete_account_confirm_item_marketplace: 'I know I will no longer be able to book orders via Food delivery marketplace.',
  delete_account_final_heading: 'Confirm you are happy to proceed',
  delete_account_final_description: 'Please note this is permanent and can\'t be undone. To confirm deleting your account, please review your email below:',
  delete_account_email_label: 'Email',
  delete_account_email_placeholder: 'your@email.com',
  delete_account_cta_continue: 'Continue',
  delete_account_cta_delete: 'Delete account',
  delete_account_close: 'Close',
  delete_account_alert_title: 'Delete account',
  delete_account_alert_message: 'Are you sure you want to permanently delete your account? This action cannot be undone.',
  delete_account_alert_cancel: 'Cancel',
  delete_account_alert_confirm: 'Delete',
  // Color mode screen
  color_mode_title: 'App color mode',
  color_mode_section_label: 'Select app color mode',
  color_mode_system: 'Default System',
  color_mode_light: 'Light',
  color_mode_dark: 'Dark',
  // Language screen
  language_title: 'App languages',
  language_section_label: 'Select language',
  language_english: 'English',
  language_french: 'French',
};

export default en;
