const fr = {
  label: 'Livraisons',
  description: 'Commandez auprès de magasins ou de vendeurs.',
  header_title: 'Livraisons',
  header_subtitle: 'Choisissez un type de livraison',
  single_vendor_title: 'Vendeur Unique',
  single_vendor_desc: 'Commandez auprès de votre magasin préféré.',
  multi_vendor_title: 'Multi Vendeurs',
  multi_vendor_desc: 'Parcourez et commandez auprès de plusieurs magasins.',
  chain_title: 'Chaîne',
  chain_desc: 'Commandez auprès de vos chaînes préférées.',
  explore_button: 'Explorer',
  details_title: 'Détails de Livraison',
  single_vendor_home_subtitle: 'Votre magasin préféré',
  single_vendor_home_body: 'Explorez les vendeurs et services ici.',
  multi_vendor_home_subtitle: 'Parcourez plusieurs magasins',
  multi_vendor_home_body: 'Découvrez et commandez auprès de plusieurs vendeurs.',
  multi_vendor_tab_home: 'Accueil',
  multi_vendor_tab_search: 'Recherche',
  multi_vendor_tab_orders: 'Commandes',
  multi_vendor_tab_profile: 'Profil',
  multi_vendor_address_label: 'Zone 6, rue 102 Doha, Qatar',
  multi_vendor_shop_types_title: 'Types de boutiques',
  multi_vendor_top_brands_title: 'Marques populaires',
  multi_vendor_nearby_store_title: 'Magasin a proximite',
  multi_vendor_deals_title: 'Offres',
  multi_vendor_order_again_title: 'Commander a nouveau 😋',
  multi_vendor_see_all: 'Voir tout',
  multi_vendor_order_again_add_item: 'Ajouter un article',
  multi_vendor_order_again_price_unavailable: 'Prix indisponible',
  multi_vendor_nearby_store_name_hardees: 'Hardee’s - Bloc Z',
  multi_vendor_nearby_store_name_subway: 'Subway - Bloc Z',
  multi_vendor_nearby_store_category_fast_food: 'Restauration rapide',
  multi_vendor_nearby_store_category_pure_veg: 'Vegetarien',
  multi_vendor_nearby_store_review_count: '(5000+)',
  multi_vendor_nearby_store_delivery_fee: '$2',
  multi_vendor_nearby_store_delivery_time: '30 min',
  multi_vendor_nearby_store_distance: '1.7 km',
  multi_vendor_sponsored_label: 'Sponsorisé',
  multi_vendor_cart_label: 'Panier',
  multi_vendor_shop_type_gift: 'Livraison de cadeaux',
  multi_vendor_shop_type_milk: 'Livraison de lait',
  multi_vendor_shop_type_flower: 'Livraison de fleurs',
  multi_vendor_shop_type_liquor: 'Livraison d’alcool',
  multi_vendor_shop_type_products_empty: 'Aucun produit trouve pour ce type de boutique.',
  multi_vendor_shop_type_products_error: 'Impossible de charger les produits pour le moment.',
  chain_home_subtitle: 'Chaînes favorites',
  chain_home_body: 'Commandez auprès de vos chaînes préférées.',
  type_single_vendor_title: 'Magasin Vendeur Unique',
  type_single_vendor_desc: 'Uniquement des vendeurs premium sélectionnés',
  type_marketplace_title: 'Marketplace',
  type_marketplace_desc: 'Nombreux prestataires locaux',
  type_chain_title: 'Magasins de Chaîne',
  type_chain_desc: 'Achetez vos chaînes préférées',
  // Profile screen
  profile_personal_account: 'Compte personnel',
  profile_wallet_balance: 'Solde du portefeuille',
  profile_view_wallet: 'Voir le portefeuille',
  profile_menu_profile: 'Profil',
  profile_menu_notifications: 'Notifications',
  profile_menu_favorites: 'Favoris',
  profile_menu_coupons: 'Coupons',
  profile_menu_settings: 'Paramètres',
  profile_menu_support: 'Assistance',
  profile_menu_color_mode: 'Mode couleur',
  profile_menu_language: 'Français',
  profile_menu_logout: 'Se déconnecter',
  // My Profile screen
  my_profile_title: 'Mon profil',
  my_profile_edit: 'Modifier',
  my_profile_full_name: 'Nom complet',
  my_profile_date_of_birth: 'Date de naissance',
  my_profile_mobile_number: 'Numéro de téléphone',
  my_profile_email: 'E-mail',
  my_profile_my_addresses: 'Mes adresses',
  my_profile_add_address: 'Ajouter une adresse',
  my_profile_address_home: 'Domicile',
  my_profile_address_apartment: 'Appartement',
  my_profile_address_work: 'Travail',
  my_profile_address_other: 'Autre',
  // Profile photo modal
  photo_modal_title: 'Photo de profil',
  photo_modal_description: 'Choisissez comment mettre à jour votre photo de profil',
  photo_take_photo: 'Prendre une photo',
  photo_choose_gallery: 'Choisir dans la galerie',
  photo_cancel: 'Annuler',
  photo_permission_title: 'Autorisation requise',
  photo_permission_camera: "L'accès à la caméra est nécessaire pour prendre une photo.",
  photo_permission_gallery: "L'accès à la galerie est nécessaire pour choisir une photo.",
  photo_upload_error_title: 'Échec du téléchargement',
  photo_upload_failed: 'Impossible de mettre à jour la photo de profil.',
  // Edit Profile screen
  edit_profile_title: 'Modifier le profil',
  edit_profile_name: 'Nom',
  edit_profile_date_of_birth: 'Date de naissance',
  edit_profile_day: 'Jour',
  edit_profile_month: 'Mois',
  edit_profile_year: 'Année',
  edit_profile_gender: 'Genre',
  edit_profile_gender_placeholder: 'Sélectionner une option',
  edit_profile_save: 'Enregistrer',
  edit_profile_success: 'Succès',
  edit_profile_success_message: 'Profil mis à jour avec succès.',
  edit_profile_error: 'Erreur',
  edit_profile_name_required: 'Le nom est requis.',
  edit_profile_failed: 'Impossible de mettre à jour le profil.',
  // Address screens
  address_list_title: 'Mes adresses',
  address_add_title: 'Ajouter une adresse',
  address_edit_title: 'Modifier l\'adresse',
  address_search_placeholder: 'Rechercher une adresse',
  address_choose_on_map: 'Choisir sur la carte',
  address_recent_searches: 'Recherches récentes',
  address_no_results: 'Aucun résultat trouvé',
  address_confirm_location: 'Confirmer l\'emplacement',
  address_locating: 'Localisation…',
  address_selected_location: 'Emplacement sélectionné',
  address_location_name_placeholder: 'Nom du lieu (ex. Ma maison)',
  address_details_label: 'Détails de l\'adresse',
  address_location_type_label: 'Type de lieu',
  address_type_home: 'Domicile',
  address_type_apartment: 'Appartement',
  address_type_office: 'Bureau',
  address_type_other: 'Autre',
  address_save: 'Enregistrer l\'adresse',
  address_update: 'Mettre à jour l\'adresse',
  address_delete: 'Supprimer',
  address_delete_confirm_title: 'Supprimer l\'adresse',
  address_delete_confirm_message: 'Êtes-vous sûr de vouloir supprimer cette adresse ?',
  address_delete_cancel: 'Annuler',
  address_delete_confirm: 'Supprimer',
  address_save_error: 'Impossible d\'enregistrer l\'adresse.',
  address_delete_error: 'Impossible de supprimer l\'adresse.',
  address_save_success: 'Adresse enregistrée avec succès.',
  address_update_success: 'Adresse mise à jour avec succès.',
  address_delete_success: 'Adresse supprimée avec succès.',
  // Favourites screen
  favourites_title: 'Vos Favoris',
  favourites_empty_title: 'Aucun favori pour l\'instant',
  favourites_empty_subtitle: 'Les magasins que vous aimez apparaîtront ici.',
  favourites_error: 'Impossible de charger les favoris. Tirez vers le bas pour réessayer.',
  favourites_free_delivery: 'Livraison gratuite',
  favourites_remove: 'Retirer des favoris',
  favourites_add: 'Ajouter aux favoris',
  favourites_toggle_added: 'Ajouté aux favoris',
  favourites_toggle_removed: 'Retiré des favoris',
  favourites_toggle_error: 'Échec de la mise à jour des favoris',
  // Rate order screen
  rate_order_title: 'Évaluer votre commande',
  rate_order_heading: 'Comment était votre repas ?',
  rate_order_subheading: 'Vos commentaires nous aident à améliorer notre livraison.',
  rate_order_comment_placeholder: 'Écrivez votre expérience ici...',
  rate_order_submit: 'Soumettre',
};

export default fr;
