const fr = {
  label: 'Livraisons',
  description: 'Commandez auprès de magasins ou de vendeurs.',
  header_title: 'Livraisons',
  header_subtitle: 'Choisissez un type de livraison',
  single_vendor_title: 'Vendeur Unique',
  single_vendor_desc: 'Commandez auprès de votre magasin préféré.',
  multi_vendor_title: 'Multi Vendeurs',
  multi_vendor_desc: 'Parcourez et commandez auprès de plusieurs magasins.',
  chain_title: 'Chaîne',
  chain_desc: 'Commandez auprès de vos chaînes préférées.',
  explore_button: 'Explorer',
  details_title: 'Détails de Livraison',
  single_vendor_home_subtitle: 'Votre magasin préféré',
  single_vendor_home_body: 'Explorez les vendeurs et services ici.',
  multi_vendor_home_subtitle: 'Parcourez plusieurs magasins',
  multi_vendor_home_body: 'Découvrez et commandez auprès de plusieurs vendeurs.',
  multi_vendor_tab_home: 'Accueil',
  multi_vendor_tab_search: 'Recherche',
  multi_vendor_tab_orders: 'Commandes',
  multi_vendor_tab_profile: 'Profil',
  multi_vendor_address_label: 'Zone 6, rue 102 Doha, Qatar',
  multi_vendor_shop_types_title: 'Types de boutiques',
  multi_vendor_top_brands_title: 'Marques populaires',
  multi_vendor_nearby_store_title: 'Magasin a proximite',
  multi_vendor_deals_title: 'Offres',
  multi_vendor_see_all: 'Voir tout',
  multi_vendor_nearby_store_name_hardees: 'Hardee’s - Bloc Z',
  multi_vendor_nearby_store_name_subway: 'Subway - Bloc Z',
  multi_vendor_nearby_store_category_fast_food: 'Restauration rapide',
  multi_vendor_nearby_store_category_pure_veg: 'Vegetarien',
  multi_vendor_nearby_store_review_count: '(5000+)',
  multi_vendor_nearby_store_delivery_fee: '$2',
  multi_vendor_nearby_store_delivery_time: '30 min',
  multi_vendor_nearby_store_distance: '1.7 km',
  multi_vendor_sponsored_label: 'Sponsorisé',
  multi_vendor_cart_label: 'Panier',
  multi_vendor_shop_type_gift: 'Livraison de cadeaux',
  multi_vendor_shop_type_milk: 'Livraison de lait',
  multi_vendor_shop_type_flower: 'Livraison de fleurs',
  multi_vendor_shop_type_liquor: 'Livraison d’alcool',
  chain_home_subtitle: 'Chaînes favorites',
  chain_home_body: 'Commandez auprès de vos chaînes préférées.',
  type_single_vendor_title: 'Magasin Vendeur Unique',
  type_single_vendor_desc: 'Uniquement des vendeurs premium sélectionnés',
  type_marketplace_title: 'Marketplace',
  type_marketplace_desc: 'Nombreux prestataires locaux',
  type_chain_title: 'Magasins de Chaîne',
  type_chain_desc: 'Achetez vos chaînes préférées',
};

export default fr;
