const en = {
  label: 'Home Visits',
  description: 'Schedule trusted visits.',
  header_title: 'Home Visits',
  header_subtitle: 'On-demand services',
  single_vendor_title: 'Single Provider',
  single_vendor_desc: 'A focused experience for one provider.',
  single_vendor_categories_title: 'Categories',
  single_vendor_category_services_empty: 'No services found for this category.',
  single_vendor_home_subtitle: 'Schedule trusted home visits',
  single_vendor_home_section_empty_title: 'Nothing here yet',
  single_vendor_home_section_error_title: 'Unable to load items',
  single_vendor_home_section_error_message: 'Please try again in a moment.',
  multi_vendor_title: 'Multi Provider',
  multi_vendor_desc: 'Browse multiple home visit providers.',
  chain_title: 'Chain',
  chain_desc: 'A structured flow for service chains.',
  single_vendor_tab_home: 'Home',
  single_vendor_tab_search: 'Search',
  single_vendor_tab_orders: 'Bookings',
  single_vendor_tab_profile: 'Profile',
  single_vendor_bookings_title: 'My Booking',
  single_vendor_bookings_tab_ongoing: 'Ongoing',
  single_vendor_bookings_tab_past: 'Past',
  single_vendor_bookings_view_details: 'View details',
  single_vendor_bookings_book_again: 'Book again',
  single_vendor_favorites_title: 'Favorites',
  single_vendor_favorites_empty: 'No items are currently in the favorites list.',
  single_vendor_favorites_error: 'Unable to load favorites right now.',
  single_vendor_bookings_item: 'item',
  single_vendor_bookings_items: 'items',
  single_vendor_bookings_retry: 'Try again',
  single_vendor_bookings_error_title: 'Unable to load bookings',
  single_vendor_bookings_empty_title_ongoing: 'No ongoing bookings',
  single_vendor_bookings_empty_subtitle_ongoing: 'Your active bookings will show up here.',
  single_vendor_bookings_empty_title_past: 'No past bookings',
  single_vendor_bookings_empty_subtitle_past: 'Your completed or cancelled bookings will show up here.',
  single_vendor_bookings_empty_generic_title: 'No appointments found',
  single_vendor_bookings_empty_generic_subtitle:
    'Your upcoming and past appointments will appear when you book',
  single_vendor_bookings_empty_cta: 'Search service',
  single_vendor_booking_status_confirmed: 'Confirmed',
  single_vendor_booking_default_duration: '1 hr duration',
  single_vendor_booking_add_calendar_title: 'Add to calendar',
  single_vendor_booking_add_calendar_subtitle: 'Set yourself a reminder',
  single_vendor_booking_calendar_open_error: 'Unable to open calendar right now.',
  single_vendor_booking_manage_title: 'Manage appointment',
  single_vendor_booking_manage_subtitle: 'Reschedule or cancel your appointment',
  single_vendor_booking_track_title: 'Track Worker',
  single_vendor_booking_track_subtitle: 'Track your worker',
  single_vendor_active_service_title: 'Service Started',
  single_vendor_active_service_default_title: 'Home Deep Cleaning',
  single_vendor_active_service_default_subtitle: 'Open your active service',
  single_vendor_track_worker_title: 'Your appointment',
  single_vendor_track_worker_estimated_service_label: 'Estimated service time',
  single_vendor_track_worker_eta_label: 'Estimated arrival time',
  single_vendor_track_worker_eta_10_15: '10-15 mins',
  single_vendor_track_worker_eta_15_25: '15-25 mins',
  single_vendor_track_worker_anytime_now: 'Anytime now',
  single_vendor_track_worker_preparing_subtitle:
    'Your order has been place and worker is preparing the equipments.',
  single_vendor_track_worker_on_the_way: 'Your worker is on the way!',
  single_vendor_track_worker_anytime_subtitle: 'Anytime now! Look out for your worker.',
  single_vendor_track_worker_service_started: 'Service has begun!',
  single_vendor_track_worker_started_subtitle: 'The service is now live!',
  single_vendor_track_worker_contact_title: 'Contact your worker',
  single_vendor_track_worker_contact_subtitle: 'Ask for contactless service',
  single_vendor_track_worker_contact_unavailable: 'Worker contact is not available right now.',
  single_vendor_track_worker_appointment_details: 'Appointment details',
  single_vendor_track_worker_booking_number: 'Booking number',
  single_vendor_track_worker_appointment_address: 'Appointment address',
  single_vendor_track_worker_address_fallback: 'Address not available',
  single_vendor_track_worker_around_corner_title:
    'Get ready, our worker is just around the corner.',
  single_vendor_track_worker_around_corner_subtitle: '',
  single_vendor_track_worker_view: 'View',
  single_vendor_track_worker_payment_title: 'Job Finished! Complete your transaction',
  single_vendor_track_worker_payment_subtitle:
    'Your service has been successfully completed. Please confirm the details in this final invoice and process your payment.',
  single_vendor_track_worker_payment_by: 'Payment by',
  single_vendor_track_worker_online_payment: 'Online Payment',
  single_vendor_track_worker_pay_now: 'Pay Now',
  single_vendor_track_worker_payment_confirmed: 'Payment confirmed',
  single_vendor_track_worker_feedback_title: 'How was your experience?',
  single_vendor_track_worker_feedback_subtitle: 'Your feedback helps us improve our services.',
  single_vendor_track_worker_feedback_placeholder: 'Write your experience here...',
  single_vendor_track_worker_submit: 'Submit',
  single_vendor_track_worker_feedback_success: 'Thanks for your feedback!',
  single_vendor_track_worker_cancelled: 'Appointment cancelled',
  single_vendor_track_worker_cancelled_subtitle: 'This appointment is no longer active.',
  single_vendor_track_worker_failed: 'Service could not be completed',
  single_vendor_track_worker_failed_subtitle: 'Please contact support for help.',
  single_vendor_booking_service_title: 'Service details',
  single_vendor_booking_service_subtitle: 'Prices may vary based on additional services',
  single_vendor_booking_service_duration: '1 hr',
  single_vendor_booking_duration_job: '1 job',
  single_vendor_booking_duration_service: '1 service',
  single_vendor_booking_total: 'Total',
  single_vendor_booking_open_reviews: 'View reviews',
  single_vendor_booking_customer_note_title: 'Customer note',
  single_vendor_booking_address_title: 'Service address',
  single_vendor_booking_cancellation_title: 'Cancellation policy',
  single_vendor_booking_cancellation_body: 'Please cancel within 2 hours of your appointment',
  single_vendor_reviews_title: 'Reviews',
  single_vendor_reviews_filter_by: 'Filter by',
  single_vendor_reviews_sort_by: 'Sort by',
  single_vendor_reviews_latest: 'Latest',
  single_vendor_reviews_best: 'Best',
  single_vendor_reviews_worst: 'Worst',
  single_vendor_reviews_summary_label: '{{rating}} ({{count}})',
  single_vendor_reviews_total_label: '{{count}} reviews',
  single_vendor_reviews_empty_title: 'No reviews yet',
  single_vendor_reviews_empty_subtitle: 'Be the first to leave a review for this service.',
  single_vendor_reviews_service_home_cleaning: 'Home cleaning',
  single_vendor_reviews_service_plumber: 'Plumber',
  single_vendor_reviews_service_window_cleaning: 'Window Cleaning',
  single_vendor_reviews_service_electrician: 'Electrician',
  single_vendor_reviews_service_floor_cleaning: 'Floor Cleaning',
  single_vendor_reviews_service_washing: 'Washing',
  single_vendor_reviews_comment_1:
    "Great service! My home is spotless and smells amazing. I'll definitely book again.",
  single_vendor_reviews_comment_2:
    'Excellent cleaning! The team was punctual, friendly, and very detail-oriented.',
  single_vendor_reviews_comment_3:
    'The best service ever! My house looks brand new. I highly recommend this company.',
  single_vendor_reviews_comment_4:
    "I'm very happy with the service. The team was professional and did a fantastic job.",
  single_vendor_reviews_comment_5:
    'The team was efficient and thorough. My home has never been cleaner. Thank you!',
  single_vendor_reviews_comment_6:
    "I'm so glad I hired this company. They were on time and did an amazing job.",
  single_vendor_reviews_comment_7:
    "I'm very impressed with the quality of service. My home is now sparkling clean!",
  single_vendor_manage_appointment_title: 'Manage appointment',
  single_vendor_manage_appointment_reschedule: 'Reschedule appointment',
  single_vendor_manage_appointment_cancel: 'Cancel appointment',
  single_vendor_manage_appointment_empty_title: 'No appointments found',
  single_vendor_manage_appointment_empty_subtitle:
    'Your upcoming and past appointments will appear when you book',
  single_vendor_manage_appointment_search_service: 'Search service',
  single_vendor_cancel_appointment_heading: 'Are you sure you want to cancel appointment?',
  single_vendor_cancel_appointment_body_top:
    'If you want to change the appointment time, you can reschedule your appointment.',
  single_vendor_cancel_appointment_body_bottom:
    'Are you sure you want to cancel your appointment?',
  single_vendor_cancel_appointment_cta: 'Yes, cancel appointment',
  single_vendor_home_body: 'Basic home screen placeholder for the single provider flow.',
  single_vendor_search_body: 'Basic search screen placeholder for the single provider flow.',
  single_vendor_orders_body: 'Basic bookings screen placeholder for the single provider flow.',
  single_vendor_profile_body: 'Basic profile screen placeholder for the single provider flow.',
  multi_vendor_home_body: 'Basic home screen placeholder for the multi provider flow.',
  chain_home_body: 'Basic home screen placeholder for the chain flow.',
  logout: 'Log out',
  logout_error_title: 'Error',
  logout_error_message: 'Unable to log out right now.',
  details_title: 'Visit Details',
  details_body: 'Visit details and provider info.',
  // Address related strings
  home_visits_address_label: 'Select service location',
  add_service_address: 'Add service address',
  address_select_error: 'Failed to select address. Please try again.',
  address_selector_title: 'Select Service Location',
  address_selector_close: 'Close',
  address_selector_use_current_location: 'Use current location',
  address_selector_add_new: 'Add new address',
  single_vendor_deals_title: 'Deals',
  single_vendor_nearby_location_title: 'Nearby your location',
  single_vendor_most_popular_services_title: 'Most Popular Services',
  single_vendor_nearby_location_select_address_message:
    'Select a service address to see nearby services.',
  single_vendor_see_all: 'See all',
  clear_all: 'Clear all',
  single_vendor_home_section_empty_message: 'Check back later for more.',
  home_visits_see_all_search_placeholder: 'Search services',
  home_visits_see_all_coming_soon_title: 'Coming soon',
  home_visits_see_all_coming_soon_description:
    'This See All screen will be available for this mode soon.',
  home_visits_filter_title: 'Filter',
  home_visits_filter_close: 'Close filters',
  home_visits_filter_stock_title: 'Stock',
  home_visits_filter_stock_all: 'All',
  home_visits_filter_stock_in_stock: 'In stock',
  home_visits_filter_price_tiers: 'Price tier',
  home_visits_filter_any_price: 'Any price',
  home_visits_filter_sort_by: 'Sort by',
  home_visits_filter_sort_recommended: 'Recommended',
  home_visits_filter_sort_delivery_time: 'Delivery time',
  home_visits_filter_sort_price_low_to_high: 'Price low to high',
  home_visits_filter_sort_name: 'Name',
  home_visits_filter_sort_rating: 'Highest rating',
  home_visits_filter_clear: 'Clear',
  home_visits_filter_apply: 'Apply',
  service_details_book_service: 'Book service',
  team_schedule_title: 'Team & Schedule',
  team_schedule_team_size_title: 'Team Size',
  team_schedule_team_size_helper: 'Pricing is calculated per worker and per hour.',
  team_schedule_working_hours_title: 'Working Hours',
  team_schedule_working_hours_helper: 'Each worker is charged at $12 per hour',
  team_schedule_service_mode_title: 'Service type',
  team_schedule_service_mode_one_time_title: 'One-time Service',
  team_schedule_service_mode_one_time_description: 'Just for now',
  team_schedule_service_mode_contract_title: 'Contract',
  team_schedule_service_mode_contract_description: 'Same team works daily. Managed by our admin.',
  team_schedule_contract_range_title: 'Enter time range',
  team_schedule_contract_range_helper: 'Select time range for the contract',
  team_schedule_contract_range_custom: 'Custom',
  team_schedule_contract_range_custom_placeholder: 'Choose days, such as 1 or 2.',
  team_schedule_contract_range_add: 'Add',
  team_schedule_continue: 'Continue',
  team_schedule_custom_title: 'Enter team members',
  team_schedule_custom_helper: 'You can select up to 12 workers',
  team_schedule_custom_field_placeholder: '1 worker',
  team_schedule_custom_add: 'Add',
  team_schedule_date_time_title: 'Choose date and time',
  team_schedule_date_time_confirm: 'Confirm Date & Time',
  team_schedule_today: 'Today',
  team_worker_singular: 'worker',
  team_worker_plural: 'workers',
  team_schedule_hour_singular: 'hour',
  team_schedule_hour_plural: 'hours',
  team_schedule_day_singular: 'Day',
  team_schedule_day_plural: 'Days',
  review_confirm_title: 'Review & Confirm',
  review_confirm_home: 'Home',
  review_confirm_notes_title: 'Notes',
  review_confirm_optional: 'Optional',
  review_confirm_notes_placeholder: 'Any instructions for cleaner',
  review_confirm_schedule_for: 'Schedule for',
  review_confirm_appointment_time: 'Appointment Time',
  review_confirm_payment_section_title: 'Payment',
  review_confirm_payment_title: 'Cash',
  review_confirm_payment_card_label: '**** 9432',
  review_confirm_payment_subtitle: 'Tap here to change',
  review_confirm_choose_payment_method_title: 'Choose payment method',
  review_confirm_add_payment_method: 'Add payment method',
  review_confirm_discount_title: 'Discount code',
  review_confirm_discount_subtitle: 'Tap here to continue',
  review_confirm_discount_placeholder: 'Enter discount code',
  review_confirm_discount_use_code: 'Use promo code',
  review_confirm_discount_applied: 'Applied: {{code}}',
  review_confirm_cancellation_title: 'Cancellation policy',
  review_confirm_cancellation_body: 'Please cancel within 2 hours of your appointment',
  review_confirm_summary_title: 'Summary',
  review_confirm_summary_subtitle:
    'incl. taxes (if applicable) - Prices may vary based on additional services',
  review_confirm_footer_cta: 'Confirm',
  review_confirm_services_title: 'Selected Services',
  review_confirm_schedule_title: 'Team & Schedule',
  review_confirm_team_label: 'Team',
  review_confirm_hours_label: 'Hours',
  review_confirm_type_label: 'Type',
  review_confirm_date_time_label: 'Date & Time',
  review_confirm_cta: 'Confirm Booking',
  review_confirm_location_title: 'Service Location',
  review_confirm_location_label: 'Address',
  review_confirm_location_fallback: 'No address selected',
  review_confirm_price_title: 'Price Summary',
  review_confirm_price_services: 'Selected services',
  review_confirm_price_workers: 'Team & hours',
  review_confirm_price_total: 'Total',
  review_confirm_popup_title: 'Please Note',
  review_confirm_popup_line_one: 'Cancel at least 2 hours before your appointment.',
  review_confirm_popup_line_two: "You'll only be charged after the service is completed.",
  review_confirm_popup_accept: 'Accept and confirm',
  review_confirm_success_title: 'Booked',
  review_confirm_success_body: 'Your booking request is ready to proceed.',
  review_confirm_appointment_confirmed: 'Appointment confirmed',
  review_confirm_place_order_error_title: 'Unable to Confirm Booking',
  review_confirm_place_order_error_description:
    'Please try again in a moment.',
  team_schedule_availability_unavailable_title: 'Scheduling Unavailable',
  team_schedule_availability_unavailable_description:
    'This service center is not accepting scheduled bookings for this date.',
  team_schedule_slot_not_available_title: 'Time Slot Not Available',
  team_schedule_slot_not_available_description:
    'Selected time is not available for your team size. Please choose another time.',
  team_schedule_availability_error_title: 'Unable to Check Availability',
  team_schedule_availability_error_description:
    'Please try again in a moment.',
  ok: 'Ok',
  service_details_service_singular: 'service',
  service_details_service_plural: 'services',
  service_details_service_type_fallback: 'Service Type',
  service_details_additional_services_fallback: 'Additional Services',
  service_details_favorite_action: 'Favorite',
  service_details_share_action: 'Share',
  Nothing_here_yet: 'Nothing here yet',
  Content_for_this_section_will_appear_once_items_are_available: 'Content for this section will appear once items are available.',
  home_visits_settings_body: 'Settings flow for home visits will be added next.',
  home_visits_support_body: 'Support flow for home visits will be added next.',
  home_visits_wallet_body: 'Wallet flow for home visits will be added next.',
  support_call_action: 'Call support',
  home_visits_support_back_action: 'Go back',
  home_visits_support_greeting: 'Hi {{name}}!',
  home_visits_support_guest_name: 'there',
  home_visits_support_headline: 'What do you need help with today?',
  home_visits_support_browse_topics: 'Browse help topics',
  home_visits_support_topic_faq: 'Frequently asked questions',
  home_visits_support_topic_conversations: 'My conversations',
  home_visits_support_topic_tickets: 'My tickets',
  home_visits_support_issue_prompt: 'Didn’t find what you need?',
  home_visits_support_issue_placeholder: 'Select an issue type',
  home_visits_support_issue_select_title: 'Select an issue',
  home_visits_support_issue_booking: 'Booking support',
  home_visits_support_issue_reschedule: 'Cancel or reschedule',
  home_visits_support_issue_payment: 'Payment issue',
  home_visits_support_issue_joining_as_a_business:
    'I’m interested in joining Home Services as a business',
  home_visits_support_issue_business_support:
    'I already have a business account and need support',
  home_visits_support_issue_appointment_support:
    'I booked an appointment with a business on Home Services',
  home_visits_support_close_action: 'Close support form',
  home_visits_support_form_how_help_label: 'How can we help?',
  home_visits_support_form_email_label: 'Email',
  home_visits_support_form_email_helper:
    'If you have a Home Services account, enter the email address you log in with',
  home_visits_support_form_full_name_label: 'Full name',
  home_visits_support_form_full_name_placeholder: 'Enter your name',
  home_visits_support_form_country_region_label: 'Country / Region',
  home_visits_support_form_country_region_placeholder: 'Please select',
  home_visits_support_form_mobile_number_label: 'Mobile number',
  home_visits_support_form_mobile_number_placeholder: '+61 333 000 0000',
  home_visits_support_form_business_name_label: 'Business name',
  home_visits_support_form_business_type_label: 'Business type',
  home_visits_support_form_business_type_placeholder: 'Please select',
  home_visits_support_form_team_size_label: 'Team size',
  home_visits_support_form_team_size_placeholder: 'Please select',
  home_visits_support_form_reason_label: 'Reason for contact',
  home_visits_support_form_reason_placeholder: 'Please select',
  home_visits_support_form_reason_account_setup: 'Account setup',
  home_visits_support_form_reason_add_on_integrations: 'Add-ons and integrations',
  home_visits_support_form_reason_addons_integrations: 'Add-ons and integrations',
  home_visits_support_form_reason_using_the_app: 'Using the app',
  home_visits_support_form_reason_payments_and_payouts: 'Payments and payouts',
  home_visits_support_form_reason_technical_issues: 'Technical issues',
  home_visits_support_form_reason_my_orders: 'My appointments',
  home_visits_support_form_reason_payments_and_purchases: 'Payments and purchases',
  home_visits_support_form_reason_reviews: 'Reviews',
  home_visits_support_form_reason_emails_and_notifications: 'Emails and notifications',
  home_visits_support_form_reason_delete_my_account: 'Delete my account',
  home_visits_support_form_reason_other: 'Other',
  home_visits_support_form_country_united_states: 'United States',
  home_visits_support_form_country_canada: 'Canada',
  home_visits_support_form_country_united_kingdom: 'United Kingdom',
  home_visits_support_form_country_australia: 'Australia',
  home_visits_support_form_country_france: 'France',
  home_visits_support_form_business_description_label:
    'Is there anything in particular you want to know about Home Services?',
  home_visits_support_form_appointment_description_label:
    'Please provide us with a description of your query, including your appointment reference or invoice number',
  home_visits_support_form_description_label: 'Describe what you need help with',
  home_visits_support_form_description_placeholder: 'Enter a description...',
  home_visits_support_form_attach_title: 'Attach screenshots',
  home_visits_support_form_attach_description: 'Drop your files here',
  home_visits_support_form_attach_cta: 'Choose a file',
  home_visits_support_form_send_email: 'Send email',
  home_visits_support_form_submit_success_title: 'Ticket created',
  home_visits_support_form_submit_success_message: 'Your support ticket was sent successfully.',
  home_visits_support_form_submit_error_title: 'Ticket failed',
  home_visits_support_chat_cta: 'Chat with a person',
  home_visits_support_admin_picker_title: 'Chat with support',
  home_visits_support_admin_picker_subtitle: 'Choose an available support admin',
  home_visits_support_admin_picker_loading: 'Loading support admins...',
  home_visits_support_admin_picker_empty: 'No support admins available right now.',
  home_visits_support_admin_picker_row_subtitle: 'Support admin',
  home_visits_support_faq_title: 'Frequently asked questions',
  home_visits_support_faq_item_1: 'How to book an appointment',
  home_visits_support_faq_item_2: 'How do I cancel or reschedule my appointment?',
  home_visits_support_faq_item_3: 'What payment methods are accepted?',
  home_visits_support_faq_item_4: 'Can I bring a friend to my appointment?',
  home_visits_support_faq_item_5: 'What is your cancellation policy?',
  home_visits_support_faq_item_6: 'Do you offer any discounts or promotions?',
  home_visits_support_conversations_title: 'My conversations',
  home_visits_support_conversations_loading: 'Loading conversations...',
  home_visits_support_conversations_empty: 'No conversations found yet.',
  home_visits_support_tickets_title: 'My tickets',
  home_visits_support_tickets_heading: 'My ticket',
  home_visits_support_tickets_search_action: 'Search tickets',
  home_visits_support_tickets_loading: 'Loading tickets...',
  home_visits_support_tickets_empty: 'No tickets found yet.',
  home_visits_support_tickets_order_id: 'Order ID: {{orderId}}',
  home_visits_support_ticket_fallback_title: 'Support ticket',
  home_visits_support_chat_agent_fallback: 'Support agent',
  home_visits_support_chat_empty_message: 'No messages yet',
  home_visits_support_chat_title: 'Salon Support',
  home_visits_support_chat_empty: 'No messages yet. Start by writing a message below.',
  home_visits_support_chat_input_placeholder: 'Enter your concern...',
  Unable_to_load_items: 'Unable to load items',
  Please_try_again_in_a_moment: 'Please try again in a moment.',
  // Search related translations
  services: 'Services',
  see_all: 'See all',
  off: 'off'
};

export default en;
