const en = {
  label: 'Home Visits',
  description: 'Schedule trusted visits.',
  header_title: 'Home Visits',
  header_subtitle: 'On-demand services',
  single_vendor_title: 'Single Provider',
  single_vendor_desc: 'A focused experience for one provider.',
  single_vendor_categories_title: 'Categories',
  single_vendor_category_services_empty: 'No services found for this category.',
  single_vendor_home_subtitle: 'Schedule trusted home visits',
  single_vendor_home_section_empty_title: 'Nothing here yet',
  single_vendor_home_section_error_title: 'Unable to load items',
  single_vendor_home_section_error_message: 'Please try again in a moment.',
  multi_vendor_title: 'Multi Provider',
  multi_vendor_desc: 'Browse multiple home visit providers.',
  chain_title: 'Chain',
  chain_desc: 'A structured flow for service chains.',
  single_vendor_tab_home: 'Home',
  single_vendor_tab_search: 'Search',
  single_vendor_tab_orders: 'Bookings',
  single_vendor_tab_profile: 'Profile',
  single_vendor_bookings_title: 'My Booking',
  single_vendor_bookings_tab_ongoing: 'Ongoing',
  single_vendor_bookings_tab_past: 'Past',
  single_vendor_bookings_view_details: 'View details',
  single_vendor_bookings_book_again: 'Book again',
  single_vendor_bookings_item: 'item',
  single_vendor_bookings_items: 'items',
  single_vendor_bookings_retry: 'Try again',
  single_vendor_bookings_error_title: 'Unable to load bookings',
  single_vendor_bookings_empty_title_ongoing: 'No ongoing bookings',
  single_vendor_bookings_empty_subtitle_ongoing: 'Your active bookings will show up here.',
  single_vendor_bookings_empty_title_past: 'No past bookings',
  single_vendor_bookings_empty_subtitle_past: 'Your completed or cancelled bookings will show up here.',
  single_vendor_booking_status_confirmed: 'Confirmed',
  single_vendor_booking_default_duration: '1 hr duration',
  single_vendor_booking_add_calendar_title: 'Add to calendar',
  single_vendor_booking_add_calendar_subtitle: 'Set yourself a reminder',
  single_vendor_booking_calendar_open_error: 'Unable to open calendar right now.',
  single_vendor_booking_manage_title: 'Manage appointment',
  single_vendor_booking_manage_subtitle: 'Reschedule or cancel your appointment',
  single_vendor_booking_track_title: 'Track Worker',
  single_vendor_booking_track_subtitle: 'Track your worker',
  single_vendor_booking_service_title: 'Service details',
  single_vendor_booking_service_subtitle: 'Prices may vary based on additional services',
  single_vendor_booking_service_duration: '1 hr',
  single_vendor_booking_duration_job: '1 job',
  single_vendor_booking_duration_service: '1 service',
  single_vendor_booking_total: 'Total',
  single_vendor_booking_customer_note_title: 'Customer note',
  single_vendor_booking_address_title: 'Service address',
  single_vendor_booking_cancellation_title: 'Cancellation policy',
  single_vendor_booking_cancellation_body: 'Please cancel within 2 hours of your appointment',
  single_vendor_manage_appointment_title: 'Manage appointment',
  single_vendor_manage_appointment_reschedule: 'Reschedule appointment',
  single_vendor_manage_appointment_cancel: 'Cancel appointment',
  single_vendor_cancel_appointment_heading: 'Are you sure you want to cancel appointment?',
  single_vendor_cancel_appointment_body_top:
    'If you want to change the appointment time, you can reschedule your appointment.',
  single_vendor_cancel_appointment_body_bottom:
    'Are you sure you want to cancel your appointment?',
  single_vendor_cancel_appointment_cta: 'Yes, cancel appointment',
  single_vendor_home_body: 'Basic home screen placeholder for the single provider flow.',
  single_vendor_search_body: 'Basic search screen placeholder for the single provider flow.',
  single_vendor_orders_body: 'Basic bookings screen placeholder for the single provider flow.',
  single_vendor_profile_body: 'Basic profile screen placeholder for the single provider flow.',
  multi_vendor_home_body: 'Basic home screen placeholder for the multi provider flow.',
  chain_home_body: 'Basic home screen placeholder for the chain flow.',
  logout: 'Log out',
  logout_error_title: 'Error',
  logout_error_message: 'Unable to log out right now.',
  details_title: 'Visit Details',
  details_body: 'Visit details and provider info.',
  // Address related strings
  home_visits_address_label: 'Select service location',
  add_service_address: 'Add service address',
  address_select_error: 'Failed to select address. Please try again.',
  address_selector_title: 'Select Service Location',
  address_selector_close: 'Close',
  address_selector_use_current_location: 'Use current location',
  address_selector_add_new: 'Add new address',
  single_vendor_deals_title: 'Deals',
  single_vendor_nearby_location_title: 'Nearby your location',
  single_vendor_most_popular_services_title: 'Most Popular Services',
  single_vendor_nearby_location_select_address_message:
    'Select a service address to see nearby services.',
  single_vendor_see_all: 'See all',
  clear_all: 'Clear all',
  single_vendor_home_section_empty_message: 'Check back later for more.',
  home_visits_see_all_search_placeholder: 'Search services',
  home_visits_see_all_coming_soon_title: 'Coming soon',
  home_visits_see_all_coming_soon_description:
    'This See All screen will be available for this mode soon.',
  home_visits_filter_title: 'Filter',
  home_visits_filter_close: 'Close filters',
  home_visits_filter_stock_title: 'Stock',
  home_visits_filter_stock_all: 'All',
  home_visits_filter_stock_in_stock: 'In stock',
  home_visits_filter_price_tiers: 'Price tier',
  home_visits_filter_any_price: 'Any price',
  home_visits_filter_sort_by: 'Sort by',
  home_visits_filter_sort_recommended: 'Recommended',
  home_visits_filter_sort_delivery_time: 'Delivery time',
  home_visits_filter_sort_price_low_to_high: 'Price low to high',
  home_visits_filter_sort_name: 'Name',
  home_visits_filter_sort_rating: 'Highest rating',
  home_visits_filter_clear: 'Clear',
  home_visits_filter_apply: 'Apply',
  service_details_book_service: 'Book service',
  service_details_service_singular: 'service',
  service_details_service_plural: 'services',
  service_details_service_type_fallback: 'Service Type',
  service_details_additional_services_fallback: 'Additional Services',
  Nothing_here_yet: 'Nothing here yet',
  Content_for_this_section_will_appear_once_items_are_available: 'Content for this section will appear once items are available.',
  home_visits_settings_body: 'Settings flow for home visits will be added next.',
  home_visits_support_body: 'Support flow for home visits will be added next.',
  home_visits_wallet_body: 'Wallet flow for home visits will be added next.',
  Unable_to_load_items: 'Unable to load items',
  Please_try_again_in_a_moment: 'Please try again in a moment.',
  // Search related translations
  services: 'Services',
  see_all: 'See all',
};

export default en;
