const en = {
  label: 'Home Visits',
  description: 'Schedule trusted visits.',
  header_title: 'Home Visits',
  header_subtitle: 'On-demand services',
  single_vendor_title: 'Single Provider',
  single_vendor_desc: 'A focused experience for one provider.',
  single_vendor_categories_title: 'Categories',
  single_vendor_category_services_empty: 'No services found for this category.',
  single_vendor_home_subtitle: 'Schedule trusted home visits',
  single_vendor_home_section_empty_title: 'Nothing here yet',
  single_vendor_home_section_error_title: 'Unable to load items',
  single_vendor_home_section_error_message: 'Please try again in a moment.',
  multi_vendor_title: 'Multi Provider',
  multi_vendor_desc: 'Browse multiple home visit providers.',
  chain_title: 'Chain',
  chain_desc: 'A structured flow for service chains.',
  single_vendor_tab_home: 'Home',
  single_vendor_tab_search: 'Search',
  single_vendor_tab_orders: 'Orders',
  single_vendor_tab_profile: 'Profile',
  single_vendor_home_body: 'Basic home screen placeholder for the single provider flow.',
  single_vendor_search_body: 'Basic search screen placeholder for the single provider flow.',
  single_vendor_orders_body: 'Basic orders screen placeholder for the single provider flow.',
  single_vendor_profile_body: 'Basic profile screen placeholder for the single provider flow.',
  multi_vendor_home_body: 'Basic home screen placeholder for the multi provider flow.',
  chain_home_body: 'Basic home screen placeholder for the chain flow.',
  logout: 'Log out',
  logout_error_title: 'Error',
  logout_error_message: 'Unable to log out right now.',
  details_title: 'Visit Details',
  details_body: 'Visit details and provider info.',
  // Address related strings
  home_visits_address_label: 'Select service location',
  add_service_address: 'Add service address',
  address_select_error: 'Failed to select address. Please try again.',
  address_selector_title: 'Select Service Location',
  address_selector_close: 'Close',
  address_selector_use_current_location: 'Use current location',
  address_selector_add_new: 'Add new address',
  single_vendor_deals_title: 'Deals',
  single_vendor_nearby_location_title: 'Nearby your location',
  single_vendor_most_popular_services_title: 'Most Popular Services',
  single_vendor_nearby_location_select_address_message:
    'Select a service address to see nearby services.',
  single_vendor_see_all: 'See all',
  single_vendor_home_section_empty_message: 'Check back later for more.',
  service_details_book_service: 'Book service',
  service_details_service_singular: 'service',
  service_details_service_plural: 'services',
  service_details_service_type_fallback: 'Service Type',
  service_details_additional_services_fallback: 'Additional Services',
  Nothing_here_yet: 'Nothing here yet',
  Content_for_this_section_will_appear_once_items_are_available: 'Content for this section will appear once items are available.',
  home_visits_settings_body: 'Settings flow for home visits will be added next.',
  home_visits_support_body: 'Support flow for home visits will be added next.',
  home_visits_wallet_body: 'Wallet flow for home visits will be added next.',
  Unable_to_load_items: 'Unable to load items',
  Please_try_again_in_a_moment: 'Please try again in a moment.',
};

export default en;
