const fr = {
  label: 'Visites à Domicile',
  description: 'Planifiez des visites de confiance.',
  header_title: 'Visites à Domicile',
  header_subtitle: 'Services à la demande',
  single_vendor_title: 'Prestataire Unique',
  single_vendor_desc: 'Une expérience ciblée pour un seul prestataire.',
  single_vendor_categories_title: 'Catégories',
  single_vendor_category_services_empty: 'Aucun service trouvé pour cette catégorie.',
  multi_vendor_title: 'Multi Prestataires',
  multi_vendor_desc: 'Parcourez plusieurs prestataires de visites à domicile.',
  chain_title: 'Chaîne',
  chain_desc: 'Un flux structuré pour les chaînes de services.',
  single_vendor_tab_home: 'Accueil',
  single_vendor_tab_search: 'Recherche',
  single_vendor_tab_orders: 'Commandes',
  single_vendor_tab_profile: 'Profil',
  single_vendor_home_body: 'Écran d’accueil de base pour le flux à prestataire unique.',
  single_vendor_search_body: 'Écran de recherche de base pour le flux à prestataire unique.',
  single_vendor_orders_body: 'Écran de commandes de base pour le flux à prestataire unique.',
  single_vendor_profile_body: 'Écran de profil de base pour le flux à prestataire unique.',
  multi_vendor_home_body: 'Écran d’accueil de base pour le flux multi prestataires.',
  chain_home_body: 'Écran d’accueil de base pour le flux chaîne.',
  logout: 'Se déconnecter',
  logout_error_title: 'Erreur',
  logout_error_message: 'Impossible de vous déconnecter pour le moment.',
  details_title: 'Détails de la Visite',
  details_body: 'Détails de la visite et informations du prestataire.',
  // Address related strings
  single_vendor_home_subtitle: 'Planifiez des visites à domicile de confiance',
  single_vendor_home_section_empty_title: 'Rien à afficher pour le moment',
  single_vendor_home_section_error_title: 'Impossible de charger les éléments',
  single_vendor_home_section_error_message: 'Veuillez réessayer dans un instant.',
  home_visits_address_label: 'Sélectionner le lieu de service',
  add_service_address: 'Ajouter une adresse de service',
  address_select_error: 'Échec de la sélection de l\'adresse. Veuillez réessayer.',
  address_selector_title: 'Sélectionner le Lieu de Service',
  address_selector_close: 'Fermer',
  address_selector_use_current_location: 'Utiliser la position actuelle',
  address_selector_add_new: 'Ajouter une nouvelle adresse',
  single_vendor_deals_title:'accords',
  single_vendor_see_all: 'voir tout',
};

export default fr;
