const fr = {
  label: 'Visites à Domicile',
  description: 'Planifiez des visites de confiance.',
  header_title: 'Visites à Domicile',
  header_subtitle: 'Services à la demande',
  single_vendor_title: 'Prestataire Unique',
  single_vendor_desc: 'Une expérience ciblée pour un seul prestataire.',
  single_vendor_categories_title: 'Catégories',
  single_vendor_category_services_empty: 'Aucun service trouvé pour cette catégorie.',
  multi_vendor_title: 'Multi Prestataires',
  multi_vendor_desc: 'Parcourez plusieurs prestataires de visites à domicile.',
  chain_title: 'Chaîne',
  chain_desc: 'Un flux structuré pour les chaînes de services.',
  single_vendor_tab_home: 'Accueil',
  single_vendor_tab_search: 'Recherche',
  single_vendor_tab_orders: 'Réservations',
  single_vendor_tab_profile: 'Profil',
  single_vendor_bookings_title: 'Ma réservation',
  single_vendor_bookings_tab_ongoing: 'En cours',
  single_vendor_bookings_tab_past: 'Passées',
  single_vendor_bookings_view_details: 'Voir les détails',
  single_vendor_bookings_book_again: 'Réserver à nouveau',
  single_vendor_favorites_title: 'Favoris',
  single_vendor_favorites_empty: 'Aucun élément n’est actuellement dans la liste des favoris.',
  single_vendor_favorites_error: 'Impossible de charger les favoris pour le moment.',
  single_vendor_bookings_item: 'article',
  single_vendor_bookings_items: 'articles',
  single_vendor_bookings_retry: 'Réessayer',
  single_vendor_bookings_error_title: 'Impossible de charger les réservations',
  single_vendor_bookings_empty_title_ongoing: 'Aucune réservation en cours',
  single_vendor_bookings_empty_subtitle_ongoing: 'Vos réservations actives apparaîtront ici.',
  single_vendor_bookings_empty_title_past: 'Aucune réservation passée',
  single_vendor_bookings_empty_subtitle_past: 'Vos réservations terminées ou annulées apparaîtront ici.',
  single_vendor_booking_status_confirmed: 'Confirmée',
  single_vendor_booking_default_duration: 'Durée de 1 h',
  single_vendor_booking_add_calendar_title: 'Ajouter au calendrier',
  single_vendor_booking_add_calendar_subtitle: 'Définissez un rappel',
  single_vendor_booking_calendar_open_error: 'Impossible d’ouvrir le calendrier pour le moment.',
  single_vendor_booking_manage_title: 'Gérer le rendez-vous',
  single_vendor_booking_manage_subtitle: 'Reprogrammez ou annulez votre rendez-vous',
  single_vendor_booking_track_title: 'Suivre le prestataire',
  single_vendor_booking_track_subtitle: 'Suivez votre prestataire',
  single_vendor_booking_service_title: 'Détails du service',
  single_vendor_booking_service_subtitle: 'Les prix peuvent varier selon les services supplémentaires',
  single_vendor_booking_service_duration: '1 h',
  single_vendor_booking_duration_job: '1 tâche',
  single_vendor_booking_duration_service: '1 service',
  single_vendor_booking_total: 'Total',
  single_vendor_booking_customer_note_title: 'Note du client',
  single_vendor_booking_address_title: 'Adresse de service',
  single_vendor_booking_cancellation_title: 'Politique d’annulation',
  single_vendor_booking_cancellation_body: 'Veuillez annuler dans les 2 heures suivant votre rendez-vous',
  single_vendor_manage_appointment_title: 'Gérer le rendez-vous',
  single_vendor_manage_appointment_reschedule: 'Reprogrammer le rendez-vous',
  single_vendor_manage_appointment_cancel: 'Annuler le rendez-vous',
  single_vendor_cancel_appointment_heading: 'Êtes-vous sûr de vouloir annuler le rendez-vous ?',
  single_vendor_cancel_appointment_body_top:
    'Si vous souhaitez modifier l’heure du rendez-vous, vous pouvez le reprogrammer.',
  single_vendor_cancel_appointment_body_bottom:
    'Êtes-vous sûr de vouloir annuler votre rendez-vous ?',
  single_vendor_cancel_appointment_cta: 'Oui, annuler le rendez-vous',
  single_vendor_home_body: 'Écran d’accueil de base pour le flux à prestataire unique.',
  single_vendor_search_body: 'Écran de recherche de base pour le flux à prestataire unique.',
  single_vendor_orders_body: 'Écran de réservations de base pour le flux à prestataire unique.',
  single_vendor_profile_body: 'Écran de profil de base pour le flux à prestataire unique.',
  multi_vendor_home_body: 'Écran d’accueil de base pour le flux multi prestataires.',
  chain_home_body: 'Écran d’accueil de base pour le flux chaîne.',
  logout: 'Se déconnecter',
  logout_error_title: 'Erreur',
  logout_error_message: 'Impossible de vous déconnecter pour le moment.',
  details_title: 'Détails de la Visite',
  details_body: 'Détails de la visite et informations du prestataire.',
  // Address related strings
  single_vendor_home_subtitle: 'Planifiez des visites à domicile de confiance',
  single_vendor_home_section_empty_title: 'Rien à afficher pour le moment',
  single_vendor_home_section_error_title: 'Impossible de charger les éléments',
  single_vendor_home_section_error_message: 'Veuillez réessayer dans un instant.',
  home_visits_address_label: 'Sélectionner le lieu de service',
  add_service_address: 'Ajouter une adresse de service',
  address_select_error: 'Échec de la sélection de l\'adresse. Veuillez réessayer.',
  address_selector_title: 'Sélectionner le Lieu de Service',
  address_selector_close: 'Fermer',
  address_selector_use_current_location: 'Utiliser la position actuelle',
  address_selector_add_new: 'Ajouter une nouvelle adresse',
  single_vendor_deals_title:'accords',
  single_vendor_nearby_location_title: 'Pres de votre emplacement',
  single_vendor_most_popular_services_title: 'Services les plus populaires',
  single_vendor_nearby_location_select_address_message:
    'Selectionnez une adresse de service pour voir les services a proximite.',
  single_vendor_see_all: 'voir tout',
  clear_all: 'Tout effacer',
  single_vendor_home_section_empty_message: 'Revenez plus tard pour en savoir plus.',
  home_visits_see_all_search_placeholder: 'Rechercher des services',
  home_visits_see_all_coming_soon_title: 'Bientôt disponible',
  home_visits_see_all_coming_soon_description:
    'Cet écran Voir tout sera bientôt disponible pour ce mode.',
  home_visits_filter_title: 'Filtrer',
  home_visits_filter_close: 'Fermer les filtres',
  home_visits_filter_stock_title: 'Stock',
  home_visits_filter_stock_all: 'Tous',
  home_visits_filter_stock_in_stock: 'En stock',
  home_visits_filter_price_tiers: 'Niveau de prix',
  home_visits_filter_any_price: 'Tous les prix',
  home_visits_filter_sort_by: 'Trier par',
  home_visits_filter_sort_recommended: 'Recommandé',
  home_visits_filter_sort_delivery_time: 'Temps de livraison',
  home_visits_filter_sort_price_low_to_high: 'Prix croissant',
  home_visits_filter_sort_name: 'Nom',
  home_visits_filter_sort_rating: 'Meilleure note',
  home_visits_filter_clear: 'Effacer',
  home_visits_filter_apply: 'Appliquer',
  service_details_book_service: 'Reserver le service',
  team_schedule_title: 'Equipe et Planning',
  team_schedule_team_size_title: "Taille de l'equipe",
  team_schedule_team_size_helper: 'Le prix est calcule par travailleur et par heure.',
  team_schedule_working_hours_title: 'Heures de travail',
  team_schedule_working_hours_helper: 'Chaque travailleur est facture a 12 $ par heure',
  team_schedule_service_mode_title: 'Type de service',
  team_schedule_service_mode_one_time_title: 'Service ponctuel',
  team_schedule_service_mode_one_time_description: 'Juste pour maintenant',
  team_schedule_service_mode_contract_title: 'Contrat',
  team_schedule_service_mode_contract_description: "La meme equipe travaille chaque jour. Gere par notre admin.",
  team_schedule_continue: 'Continuer',
  team_schedule_custom_title: "Entrer les membres de l'equipe",
  team_schedule_custom_helper: 'Vous pouvez selectionner jusqu a 12 travailleurs',
  team_schedule_custom_field_placeholder: '1 travailleur',
  team_schedule_custom_add: 'Ajouter',
  team_schedule_date_time_title: "Choisir la date et l'heure",
  team_schedule_date_time_confirm: "Confirmer la date et l'heure",
  team_schedule_today: "Aujourd'hui",
  team_worker_singular: 'travailleur',
  team_worker_plural: 'travailleurs',
  team_schedule_hour_singular: 'heure',
  team_schedule_hour_plural: 'heures',
  review_confirm_title: 'Verifier et confirmer',
  review_confirm_home: 'Domicile',
  review_confirm_notes_title: 'Notes',
  review_confirm_optional: 'Optionnel',
  review_confirm_notes_placeholder: 'Instructions pour le technicien',
  review_confirm_schedule_for: 'Planifie pour',
  review_confirm_appointment_time: 'Heure du rendez-vous',
  review_confirm_payment_section_title: 'Paiement',
  review_confirm_payment_title: 'Especes',
  review_confirm_payment_card_label: '**** 9432',
  review_confirm_payment_subtitle: 'Touchez pour changer',
  review_confirm_choose_payment_method_title: 'Choisir le mode de paiement',
  review_confirm_add_payment_method: 'Ajouter un mode de paiement',
  review_confirm_discount_title: 'Code promo',
  review_confirm_discount_subtitle: 'Touchez pour continuer',
  review_confirm_discount_placeholder: 'Entrer le code promo',
  review_confirm_discount_use_code: 'Utiliser le code promo',
  review_confirm_discount_applied: 'Applique : {{code}}',
  review_confirm_cancellation_title: "Politique d'annulation",
  review_confirm_cancellation_body: 'Veuillez annuler au moins 2 heures avant votre rendez-vous',
  review_confirm_summary_title: 'Resume',
  review_confirm_summary_subtitle:
    'Taxes incluses (si applicables) • Les prix peuvent varier selon les services supplementaires',
  review_confirm_footer_cta: 'Confirmer',
  review_confirm_services_title: 'Services selectionnes',
  review_confirm_schedule_title: 'Equipe et planning',
  review_confirm_team_label: 'Equipe',
  review_confirm_hours_label: 'Heures',
  review_confirm_type_label: 'Type',
  review_confirm_date_time_label: 'Date et heure',
  review_confirm_cta: 'Confirmer la reservation',
  review_confirm_location_title: 'Lieu du service',
  review_confirm_location_label: 'Adresse',
  review_confirm_location_fallback: 'Aucune adresse selectionnee',
  review_confirm_price_title: 'Resume du prix',
  review_confirm_price_services: 'Services selectionnes',
  review_confirm_price_workers: 'Equipe et heures',
  review_confirm_price_total: 'Total',
  review_confirm_popup_title: 'Veuillez noter',
  review_confirm_popup_line_one: 'Annulez au moins 2 heures avant votre rendez-vous.',
  review_confirm_popup_line_two: 'Vous serez facture uniquement apres la fin du service.',
  review_confirm_popup_accept: 'Accepter et confirmer',
  review_confirm_success_title: 'Reserve',
  review_confirm_success_body: 'Votre demande de reservation est prete.',
  team_schedule_availability_unavailable_title: 'Planification indisponible',
  team_schedule_availability_unavailable_description:
    "Ce centre de service n'accepte pas de reservations planifiees pour cette date.",
  team_schedule_slot_not_available_title: 'Creneau indisponible',
  team_schedule_slot_not_available_description:
    "L'heure choisie n'est pas disponible pour la taille de votre equipe. Veuillez choisir une autre heure.",
  team_schedule_availability_error_title: "Impossible de verifier la disponibilite",
  team_schedule_availability_error_description:
    'Veuillez reessayer dans un instant.',
  ok: 'Ok',
  service_details_service_singular: 'service',
  service_details_service_plural: 'services',
  service_details_service_type_fallback: 'Type de service',
  service_details_additional_services_fallback: 'Services supplementaires',
  service_details_favorite_action: 'Favori',
  service_details_share_action: 'Partager',
  Nothing_here_yet: 'Rien ici encore',
  Content_for_this_section_will_appear_once_items_are_available: 'Le contenu de cette section apparaîtra dès que les articles seront disponibles.',
  home_visits_settings_body: 'Le flux des paramètres pour les visites à domicile sera ajouté ensuite.',
  home_visits_support_body: "Le flux d'assistance pour les visites à domicile sera ajouté ensuite.",
  home_visits_wallet_body: 'Le flux du portefeuille pour les visites à domicile sera ajouté ensuite.',
  Unable_to_load_items: 'Impossible de charger les articles',
  Please_try_again_in_a_moment: 'Veuillez réessayer dans un instant.',
  // Search related translations
  services: 'Services',
  see_all: 'Voir tout',
};

export default fr;
