const fr = {
  label: 'Visites à Domicile',
  description: 'Planifiez des visites de confiance.',
  header_title: 'Visites à Domicile',
  header_subtitle: 'Services à la demande',
  single_vendor_title: 'Prestataire Unique',
  single_vendor_desc: 'Une expérience ciblée pour un seul prestataire.',
  multi_vendor_title: 'Multi Prestataires',
  multi_vendor_desc: 'Parcourez plusieurs prestataires de visites à domicile.',
  chain_title: 'Chaîne',
  chain_desc: 'Un flux structuré pour les chaînes de services.',
  single_vendor_tab_home: 'Accueil',
  single_vendor_tab_search: 'Recherche',
  single_vendor_tab_orders: 'Commandes',
  single_vendor_tab_profile: 'Profil',
  single_vendor_home_body: 'Écran d’accueil de base pour le flux à prestataire unique.',
  single_vendor_search_body: 'Écran de recherche de base pour le flux à prestataire unique.',
  single_vendor_orders_body: 'Écran de commandes de base pour le flux à prestataire unique.',
  single_vendor_profile_body: 'Écran de profil de base pour le flux à prestataire unique.',
  multi_vendor_home_body: 'Écran d’accueil de base pour le flux multi prestataires.',
  chain_home_body: 'Écran d’accueil de base pour le flux chaîne.',
  logout: 'Se déconnecter',
  logout_error_title: 'Erreur',
  logout_error_message: 'Impossible de vous déconnecter pour le moment.',
  details_title: 'Détails de la Visite',
  details_body: 'Détails de la visite et informations du prestataire.',
};

export default fr;
