const en = {
  label: 'Ride Sharing',
  description: 'Book rides in minutes.',
  header_title: 'Ride Sharing',
  header_subtitle: 'Get to your destination',
  home_body: 'Book a ride and track it in real time.',
  ride_options_title: 'Go anywhere',
  ride_option_now_title: 'Ride',
  ride_option_now_desc: 'Request a nearby driver',
  ride_option_schedule_title: 'Scheduled',
  ride_option_schedule_desc: 'Plan a pickup in advance',
  ride_option_rental_title: 'Hourly',
  ride_option_rental_desc: 'Keep a car for hours',
  ride_option_courier_title: 'Courier',
  ride_option_courier_desc: 'Send parcels quickly',
  ride_option_women_title: 'Women Ride',
  ride_option_ac_title: 'Ride A/C',
  ride_option_premium_title: 'Premium',
  ride_search_placeholder: 'Where to & for how much?',
  ride_current_location: 'Current location',
  ride_pickup_point_label: 'Pickup point',
  ride_pickup_point_value: 'New Jersey',
  delivery_services_title: 'Get anything delivered',
  delivery_service_food_title: 'Food Delivery',
  delivery_service_food_desc: 'Meals at your doorstep',
  delivery_service_grocery_title: 'Grocery Delivery',
  delivery_service_grocery_desc: 'Fresh items in minutes',
  delivery_service_gift_title: 'Gift Delivery',
  delivery_service_gift_desc: 'Send a surprise',
  delivery_service_medicine_title: 'Medicine Delivery',
  delivery_service_medicine_desc: 'Delivered to your door',
  delivery_service_package_title: 'Package courier',
  delivery_service_package_desc: 'Send parcels quickly',
  details_title: 'Ride Details',
  details_body: 'Ride details and driver information.',
  driver_profile_title: 'Driver Profile',
  driver_profile_button: 'Driver Profile',
  // Sidebar
  logout: 'Logout',
  // Sidebar menu items
  sidebar_lo_drive: 'LO Drive',
  sidebar_lo_drive_subtitle: 'Book and manage your regular rides with easy pickup and drop-off options.',
  sidebar_reservations: 'Reservations',
  sidebar_reservations_subtitle: 'View and manage your upcoming and past reservations in one place.',
  sidebar_ride_history: 'Ride & courier history',
  sidebar_ride_history_subtitle: 'Access your completed rides and courier deliveries with full details.',
  sidebar_payment_methods: 'Payment methods',
  sidebar_payment_methods_subtitle: 'Add or Update your saved payment methods.',
  sidebar_wallet: 'Wallet',
  sidebar_wallet_subtitle: 'View and manage your balance, transactions, and payments.',
  sidebar_support: 'Support and feedback',
  sidebar_support_subtitle: 'Reach out for help or give feedback on your experience.',
  sidebar_security: 'Security and settings',
  sidebar_security_subtitle: 'Update your password and change app preferences.',
  sidebar_notifications: 'Notifications',
  sidebar_notifications_subtitle: 'Stay updated with important alerts, ride updates, offers, and account activity.',
  // Profile
  personal_info_title: 'Personal info',
  personal_info_subtitle: 'Update your personal and contact details.',
  profile_photo_title: 'Profile photo',
  profile_photo_description: 'This is the photo you would like others to see.',
  update_photo_button: 'Update photo',
  cancel_button: 'Cancel',
  label_name: 'Full Name',
  label_phone: 'Phone number',
  label_email: 'Email',
  label_first_name: 'First name',
  label_last_name: 'Last name',
  label_country_code: 'Country code',
  label_phone_number: 'Phone number',
  name_screen_title: 'Name',
  name_screen_description: 'This is the name you would like other people to use when referring you you.',
  phone_screen_title: 'Phone number',
  phone_screen_description: 'You\'ll use this number to get notifications, sign in, and recover your account.',
  phone_screen_subtitle: 'A verification code will be sent to this number',
  update_button: 'Update',
  back_button: 'Back',
  // Settings
  settings_title: 'Security and settings',
  settings_subtitle: 'Update your password and change app preferences.',
  settings_update_password: 'Update Password',
  settings_current_password_label: 'Current password',
  settings_current_password_placeholder: 'Enter current password',
  settings_new_password_label: 'New password',
  settings_new_password_placeholder: 'Enter new password',
  settings_confirm_password_label: 'Confirm password',
  settings_confirm_password_placeholder: 'Re-enter new password',
  settings_language: 'Language',
  settings_language_en: 'English (US)',
  settings_language_fr: 'French',
  settings_theme: 'Appearance',
  settings_theme_system: 'Use device settings',
  settings_theme_light: 'Light mode',
  settings_theme_dark: 'Dark mode',
  settings_terms: 'Rules and terms',
  settings_privacy: 'Privacy policy',
  settings_terms_conditions: 'Terms and conditions',
  settings_licences: 'Licences',
  settings_lorem_ipsum: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  settings_terms_conditions_subtitle: 'Please review and accept our legal terms.',
  password_min_length: 'Password must be at least 8 characters',
  password_uppercase: 'Password must contain at least one uppercase letter',
  password_lowercase: 'Password must contain at least one lowercase letter',
  password_number: 'Password must contain at least one number',
  password_special: 'Password must contain at least one special character',
  invalid_password: 'Invalid Password',
  settings_password_update_success: 'Password updated successfully',
  settings_password_update_error: 'Failed to update password. Please try again.',
  success: 'Success',
  error: 'Error',
  ok: 'OK',
  ride_address_title: 'Your Route',
  ride_address_close: 'Close',
  ride_address_from_placeholder: 'From',
  ride_address_to_placeholder: 'To',
  ride_address_choose_on_map: 'Choose on map',
  ride_address_no_results_title: 'No addresses found',
  ride_address_no_results_description: 'Try a different street, building, or landmark name.',
  ride_address_recent_empty_title: 'No recent addresses yet',
  ride_address_recent_empty_description: 'Your recent pickup and drop-off selections will appear here.',
  ride_schedule_label: 'Schedule ride',
  ride_payment_cash: 'Cash',
  ride_find_button: 'Find a ride',
  // Reservations
  reservations_title: 'Reservations',
  reservations_empty: 'No reservations yet',
  reservation_detail_title: 'Reservation detail',
  reservation_scheduled_for: 'Scheduled for',
  reservation_payment: 'Payment',
  reservation_route: 'Your ride route',
  reservation_status: 'Ride status',
  reservation_things_to_mind: 'Things to keep in mind',
  reservation_wait_time: 'Wait time',
  reservation_cancellation_policy: 'Cancellation policy',
  reservation_cancel_ride: 'Cancel the ride',
  reservation_confirm_cancel_title: 'Are you sure?',
  reservation_confirm_cancel_yes: 'Yes, cancel the ride',
  reservation_confirm_cancel_no: 'No, Continue the ride',
  reservation_status_scheduled: 'Scheduled',
  reservation_status_completed: 'Completed',
  reservation_status_cancelled: 'Cancelled by you',
  reservation_status_in_progress: 'In progress',
  reservation_more_options: 'More options',
  reservation_not_found: 'Reservation not found',
  reservation_cash: 'Cash',
  reservation_card: 'Card',
  reservation_driver_details: 'Driver details',
  reservation_rides: 'rides',
};

export default en;
