const en = {
  label: 'Ride Sharing',
  description: 'Book rides in minutes.',
  header_title: 'Ride Sharing',
  header_subtitle: 'Get to your destination',
  home_body: 'Book a ride and track it in real time.',
  ride_options_title: 'Go anywhere',
  ride_option_now_title: 'Ride',
  ride_option_now_desc: 'Request a nearby driver',
  ride_option_schedule_title: 'Scheduled',
  ride_option_schedule_desc: 'Plan a pickup in advance',
  ride_option_rental_title: 'Hourly',
  ride_option_rental_desc: 'Keep a car for hours',
  ride_option_courier_title: 'Courier',
  ride_option_courier_desc: 'Send parcels quickly',
  ride_option_women_title: 'Women Ride',
  ride_option_ac_title: 'Ride A/C',
  ride_option_premium_title: 'Premium',
  ride_search_placeholder: 'Where to & for how much?',
  ride_pickup_point_label: 'Pickup point',
  ride_pickup_point_value: 'New Jersey',
  delivery_services_title: 'Get anything delivered',
  delivery_service_food_title: 'Food Delivery',
  delivery_service_food_desc: 'Meals at your doorstep',
  delivery_service_grocery_title: 'Grocery Delivery',
  delivery_service_grocery_desc: 'Fresh items in minutes',
  delivery_service_gift_title: 'Gift Delivery',
  delivery_service_gift_desc: 'Send a surprise',
  delivery_service_medicine_title: 'Medicine Delivery',
  delivery_service_medicine_desc: 'Delivered to your door',
  delivery_service_package_title: 'Package courier',
  delivery_service_package_desc: 'Send parcels quickly',
  details_title: 'Ride Details',
  details_body: 'Ride details and driver information.',
  driver_profile_title: 'Driver Profile',
  driver_profile_button: 'Driver Profile',
  // Sidebar
  logout: 'Logout',
  // Sidebar menu items
  sidebar_lo_drive: 'LO Drive',
  sidebar_lo_drive_subtitle: 'Book and manage your regular rides with easy pickup and drop-off options.',
  sidebar_reservations: 'Reservations',
  sidebar_reservations_subtitle: 'View and manage your upcoming and past reservations in one place.',
  sidebar_ride_history: 'Ride & courier history',
  sidebar_ride_history_subtitle: 'Access your completed rides and courier deliveries with full details.',
  sidebar_payment_methods: 'Payment methods',
  sidebar_payment_methods_subtitle: 'Add or Update your saved payment methods.',
  sidebar_wallet: 'Wallet',
  sidebar_wallet_subtitle: 'View and manage your balance, transactions, and payments.',
  sidebar_support: 'Support and feedback',
  sidebar_support_subtitle: 'Reach out for help or give feedback on your experience.',
  sidebar_security: 'Security and settings',
  sidebar_security_subtitle: 'Update your password and change app preferences.',
  sidebar_notifications: 'Notifications',
  sidebar_notifications_subtitle: 'Stay updated with important alerts, ride updates, offers, and account activity.',
  // Profile
  personal_info_title: 'Personal info',
  personal_info_subtitle: 'Update your personal and contact details.',
  profile_photo_title: 'Profile photo',
  profile_photo_description: 'This is the photo you would like others to see.',
  update_photo_button: 'Update photo',
  cancel_button: 'Cancel',
  label_name: 'Full Name',
  label_phone: 'Phone number',
  label_email: 'Email',
  label_first_name: 'First name',
  label_last_name: 'Last name',
  label_country_code: 'Country code',
  label_phone_number: 'Phone number',
  name_screen_title: 'Name',
  name_screen_description: 'This is the name you would like other people to use when referring you you.',
  phone_screen_title: 'Phone number',
  phone_screen_description: 'You\'ll use this number to get notifications, sign in, and recover your account.',
  phone_screen_subtitle: 'A verification code will be sent to this number',
  update_button: 'Update',
  back_button: 'Back',
  // Settings
  settings_title: 'Security and settings',
  settings_subtitle: 'Update your password and change app preferences.',
  settings_update_password: 'Update Password',
  settings_current_password_label: 'Current password',
  settings_current_password_placeholder: 'Enter current password',
  settings_new_password_label: 'New password',
  settings_new_password_placeholder: 'Enter new password',
  settings_confirm_password_label: 'Confirm password',
  settings_confirm_password_placeholder: 'Re-enter new password',
  settings_language: 'Language',
  settings_language_en: 'English (US)',
  settings_language_fr: 'French',
  settings_theme: 'Appearance',
  settings_theme_system: 'Use device settings',
  settings_theme_light: 'Light mode',
  settings_theme_dark: 'Dark mode',
};

export default en;
