const en = {
  label: 'Ride Sharing',
  description: 'Book rides in minutes.',
  header_title: 'Ride Sharing',
  header_subtitle: 'Get to your destination',
  home_body: 'Book a ride and track it in real time.',
  ride_options_title: 'Go anywhere',
  ride_option_now_title: 'Ride',
  ride_option_now_desc: 'Request a nearby driver',
  ride_option_schedule_title: 'Scheduled',
  ride_option_schedule_desc: 'Plan a pickup in advance',
  ride_option_rental_title: 'Hourly',
  ride_option_rental_desc: 'Keep a car for hours',
  ride_option_courier_title: 'Courier',
  ride_option_courier_desc: 'Send parcels quickly',
  delivery_services_title: 'Get anything delivered',
  delivery_service_food_title: 'Food Delivery',
  delivery_service_food_desc: 'Meals at your doorstep',
  delivery_service_grocery_title: 'Grocery Delivery',
  delivery_service_grocery_desc: 'Fresh items in minutes',
  delivery_service_gift_title: 'Gift Delivery',
  delivery_service_gift_desc: 'Send a surprise',
  delivery_service_medicine_title: 'Medicine Delivery',
  delivery_service_medicine_desc: 'Delivered to your door',
  delivery_service_package_title: 'Package courier',
  delivery_service_package_desc: 'Send parcels quickly',
  details_title: 'Ride Details',
  details_body: 'Ride details and driver information.',
  driver_profile_title: 'Driver Profile',
  driver_profile_button: 'Driver Profile',
  // Sidebar
  logout: 'Logout',
  // Sidebar menu items
  sidebar_lo_drive: 'LO Drive',
  sidebar_lo_drive_subtitle: 'Book and manage your regular rides with easy pickup and drop-off options.',
  sidebar_reservations: 'Reservations',
  sidebar_reservations_subtitle: 'View and manage your upcoming and past reservations in one place.',
  sidebar_ride_history: 'Ride & courier history',
  sidebar_ride_history_subtitle: 'Access your completed rides and courier deliveries with full details.',
  sidebar_payment_methods: 'Payment methods',
  sidebar_payment_methods_subtitle: 'Add or Update your saved payment methods.',
  sidebar_wallet: 'Wallet',
  sidebar_wallet_subtitle: 'View and manage your balance, transactions, and payments.',
  sidebar_support: 'Support and feedback',
  sidebar_support_subtitle: 'Reach out for help or give feedback on your experience.',
  sidebar_security: 'Security and settings',
  sidebar_security_subtitle: 'Update your password and change app preferences.',
  sidebar_notifications: 'Notifications',
  sidebar_notifications_subtitle: 'Stay updated with important alerts, ride updates, offers, and account activity.',
};

export default en;

