const fr = {
  label: 'Covoiturage',
  description: 'Réservez des trajets en quelques minutes.',
  header_title: 'Covoiturage',
  header_subtitle: 'Atteignez votre destination',
  home_body: 'Réservez un trajet et suivez-le en temps réel.',
  ride_options_title: 'Allez partout',
  ride_option_now_title: 'Trajet',
  ride_option_now_desc: 'Trouvez un chauffeur proche',
  ride_option_schedule_title: 'Programmé',
  ride_option_schedule_desc: 'Réservez un départ à l’avance',
  ride_option_rental_title: 'Horaire',
  ride_option_rental_desc: 'Gardez une voiture plusieurs heures',
  ride_option_courier_title: 'Coursier',
  ride_option_courier_desc: 'Envoyez vos colis rapidement',
  ride_option_women_title: 'Trajet Femmes',
  ride_option_ac_title: 'Trajet A/C',
  ride_option_premium_title: 'Premium',
  ride_search_placeholder: 'Où aller & pour combien ?',
  ride_pickup_point_label: 'Point de départ',
  ride_pickup_point_value: 'New Jersey',
  delivery_services_title: 'Faites tout livrer',
  delivery_service_food_title: 'Livraison de repas',
  delivery_service_food_desc: 'Des plats à votre porte',
  delivery_service_grocery_title: 'Livraison de courses',
  delivery_service_grocery_desc: 'Produits frais rapidement',
  delivery_service_gift_title: 'Livraison de cadeau',
  delivery_service_gift_desc: 'Envoyez une surprise',
  delivery_service_medicine_title: 'Livraison de médicaments',
  delivery_service_medicine_desc: 'Livré à votre porte',
  delivery_service_package_title: 'Colis express',
  delivery_service_package_desc: 'Envoyez vos colis rapidement',
  details_title: 'Détails du Trajet',
  details_body: 'Détails du trajet et informations sur le conducteur.',
  driver_profile_title: 'Profil du Conducteur',
  driver_profile_button: 'Profil du Conducteur',
  // Sidebar
  logout: 'Déconnexion',
  // Sidebar menu items
  sidebar_lo_drive: 'LO Drive',
  sidebar_lo_drive_subtitle: 'Réservez et gérez vos trajets réguliers avec des options de prise en charge et de dépôt faciles.',
  sidebar_reservations: 'Réservations',
  sidebar_reservations_subtitle: 'Consultez et gérez vos réservations à venir et passées en un seul endroit.',
  sidebar_ride_history: 'Historique des trajets et livraisons',
  sidebar_ride_history_subtitle: 'Accédez à vos trajets et livraisons terminés avec tous les détails.',
  sidebar_payment_methods: 'Moyens de paiement',
  sidebar_payment_methods_subtitle: 'Ajoutez ou mettez à jour vos moyens de paiement enregistrés.',
  sidebar_wallet: 'Portefeuille',
  sidebar_wallet_subtitle: 'Consultez et gérez votre solde, transactions et paiements.',
  sidebar_support: 'Support et feedback',
  sidebar_support_subtitle: 'Contactez-nous pour obtenir de l\'aide ou donnez votre avis sur votre expérience.',
  sidebar_security: 'Sécurité et paramètres',
  sidebar_security_subtitle: 'Mettez à jour votre mot de passe et modifiez les préférences de l\'application.',
  sidebar_notifications: 'Notifications',
  sidebar_notifications_subtitle: 'Restez informé des alertes importantes, mises à jour des trajets, offres et activité du compte.',
  // Profile
  personal_info_title: 'Informations personnelles',
  personal_info_subtitle: 'Mettez à jour vos coordonnées personnelles et de contact.',
  profile_photo_title: 'Photo de profil',
  profile_photo_description: 'Ceci est la photo que vous souhaitez que les autres voient.',
  update_photo_button: 'Mettre à jour la photo',
  cancel_button: 'Annuler',
  label_name: 'Nom',
  label_phone: 'Numéro de téléphone',
  label_email: 'Email',
  label_first_name: 'Prénom',
  label_last_name: 'Nom',
  label_country_code: 'Indicatif pays',
  label_phone_number: 'Numéro de téléphone',
  name_screen_title: 'Nom',
  name_screen_description: 'Ceci est le nom que vous souhaitez que les autres personnes utilisent pour vous désigner.',
  phone_screen_title: 'Numéro de téléphone',
  phone_screen_description: 'Vous utiliserez ce numéro pour recevoir des notifications, vous connecter et récupérer votre compte.',
  phone_screen_subtitle: 'Un code de vérification sera envoyé à ce numéro',
  update_button: 'Mettre à jour',
  back_button: 'Retour',
};

export default fr;
